import {Document, h1, h2, p, a, i, ipa, documentToJSX} from "./formatting";

export const HistoryDocument: Document = [
  h1("History"),
  h2("Jaobon 1 (2014)"),
  p(
    "The Jaobon project was begun in September or October 2014 - the first written reference to it I have is a ",
    a("https://www.reddit.com/r/conlangs/comments/2i4l0k/introducing_jaobon_a_major_departure_from_my/", "Reddit post"),
    " from 2 Oct 2014. ",
    "The phonology was extremely similar, with the same consonant and vowel inventories, and lacking only coda ",
    ipa("/k/"), " and ", ipa("/s/"), " and the diphthong ", ipa("/oi̯/"), " relative to the current version. ",
    "This gave it a total of 192 possible roots (17 consonants times 12 finals, minus 12 impossible combinations because ",
    ipa("/ti/"), ", ", ipa("/di/"), ", ", ipa("/si/"), ", ", ipa("/hi/"), ", ",
    ipa("/ji/"), ", and ", ipa("/wu/"), " were avoided, just as in the current version of Jaobon). ",
    "However, there were some gaps - I started with 184 roots, at some point going up to 188. ",
    "A 184-root list is available in a ", a("https://www.reddit.com/r/conlangs/comments/2ihs4y/jaobon_hanzi/", "Reddit post"),
    " which also includes the CJK characters I associated with each root. A 188-root list is available in the ",
    a("https://community-courses.memrise.com/community/course/409937/basic-jaobon/", "Memrise course"),
    " I created some time later.",
  ),
  p(
    "Because the phonology and number of roots were so different, the rate of lexical similarity between 2014 ",
    "Jaobon and now is quite low, and few roots are recognizably preserved since then. A glance at my ",
    a("https://www.reddit.com/r/conlangs/comments/2i4z7k/sample_of_jaobon/", "2014 translation"),
    " of The North Wind and the Sun shows this off well: the roots which are more or less the same as their current ",
    "versions include ", i("bin"), ", ", i("i"), ", ", i("ke"),", and ", i("lai"),
    ", but overall the text is very different from an ",
    a("/texts/classics/north_wind", "up-to-date translation"), ".",
  ),
  p(
    "There are many other differences in addition to lexical. ",
    "Firstly, the grammar was fairly different ",
    "from both current Jaobon and the source languages: what are now voice particles functioned then more ",
    "like case markers, making the word order actually somewhat flexible between SVO, SOV, and OSV, and noun ",
    "phrases were strictly left-branching. ",
    "Also, roots were only sourced from ",
    "English, Spanish, and Mandarin, though a few grammatical particles were invented a priori. Lastly, there ",
    "were some orthographic differences: ", ipa("/t͡ʃ ʃ/"), " were ⟨ch sh⟩ rather than ⟨c x⟩, ",
    "and I wrote compound words without spaces.",
  ),
  h2("Subsequent projects (2015)"),
  p(
    "In those early materials, I called Jaobon \"oligosynthetic\", a term which has varying definitions but was ",
    a("https://www.reddit.com/r/conlangs/comments/2vr4fc/the_rconlangs_oligosynthesis_debate/", "in vogue"),
    " on /r/conlangs at the time to describe languages with as few as 20ish morphemes, the most well-known of which was ",
    a("https://www.reddit.com/r/Vahn/", "Vahn"), ", which boasts 37 morphemes. ",
    "(The term \"oligoanalytic\" also exists which probably better describes Jaobon and Toki Pona, though I may not ",
    "have known it at the time; under such usage, Vahn is still a good example of an oligosynthetic language as its ",
    "morphemes are only one or two phonemes, and phonological words may be multimorphemic.) ",
    "I think it's true that Jaobon was at that time as much or more a response to the oligosynthesis wave as to ",
    "Toki Pona in particular, and my intention was to create a language with a somewhat restrictive morpheme ",
    "inventory that still felt fairly natural, unlike the (in my then-perception) mind-bending and semantically ",
    "restricted and vague oligolangs."
  ),
  p(
    "In February 2015, ",
    a("https://www.reddit.com/r/conlangs/comments/2wdlcz/introducing_kus_jaaw_a_catechoradical_language/", "I declared"),
    " that 184 roots had been too few and that I was done with oligosynthesis, starting a new project that I dubbed ",
    "\"catechoradical\" - a step above oligosynthetic languages in morpheme count with 512, though still capped ",
    "very low relative to natural languages. ",
    "I have no other memories or written records of that catechoradical project and I don't think I developed it ",
    "further, but it's clear that after a few months of dabbling I was feeling quite cramped with the sub-200 ",
    "inventory of roots."
  ),
  p(
    "In fall 2015, I started work on ",
    a("https://lauvinko.conorstuartroe.com/", "Lauvìnko"), ", ",
    "a naturalistic language set in early modern Malaysia, and in connection I created a sibling project ",
    a("https://www.reddit.com/r/conlangs/comments/3nhx7o/basabano_my_catechoradical_creole/", "Basabano"), ", ",
    "a language sharing many traits with Jaobon but which was framed as a creole between Malay, English, ",
    "Portuguese (≈ Spanish), Hokkien (≈ Mandarin), Hindi, and Arabic, a plausible occurrence in that time and ",
    "place but also - shock and awe - a language with few lexemes, all of which derive from the most widely ",
    "spoken languages in the world and is easy to learn. ",
    "I created about ",
    a("https://docs.google.com/spreadsheets/d/11-Kuwv3nf6l3lt45ftNZQLh-IzqbOM5-fMGuVmSqnRE/edit?usp=sharing", "250 roots"), ", ",
    "though the bisyllabic phonology permitted thousands and I expressed an intention to create at least several hundred. ",
    "I also evidently gained enough facility in the language to ",
    a("https://www.reddit.com/r/conlangs/comments/3odam9/a_journal_entry_in_basabano_it_may_not_look_like/", "journal in it"), ", ",
    "but work stalled on the project at some point. ",
    "I think I must have concluded it was infeasible to combine the naturalistic origin story and the very much ",
    "engineered nature of an oligoanalytic language. ",
  ),
  p(
    "Nonetheless, Basabano seems to have planted a couple of ideas in my mind that would be remembered when I ",
    "came back around to Jaobon. For one, Basabano permitted four consonant codas: ",
    ipa("/n s k l/"), ", ",
    "laying the groundwork for adding coda ",
    ipa("/s k/"), " ",
    "to Jaobon (I must have realized at some point that coda ",
    ipa("/l/"), " ",
    "can actually be quite difficult). ",
    "Also, perhaps Basabano made me more open to admitting etymologies from outside the core three languages."
  ),
  h2("Jaobon 2: the Return of Jaobon (2019)"),
  p(
    "In summer 2019, I came back onto the oligo scene with a new edition of Jaobon, which this time looks very much ",
    "like the current version. It has 325 roots, which are only recorded in a ",
    a("https://community-courses.memrise.com/community/course/5526464/jaobon-2/1/", "second Memrise course"), ". ",
    "Without doing a real count, at a glance it looks like about 80% of the roots are still the same in current ",
    "Jaobon, and the phonology looks much more like the current version, with the new coda consonants and 350 possible roots. ",
    "I have no other materials in or about this version of Jaobon and don't even have any sentences written in it, ",
    "but judging by the set of grammatical particles I'd say the intended grammar was more or less in line with the ",
    "current version as well.",
  ),
  h2("Jaobon 3: In Code! (2023-)"),
  p(
    "In 2020 I started my career as a professional software engineer, and around that time every one of my hobbies ",
    "became subsumed into being coding projects (seriously - ",
    a("https://github.com/cstuartroe/membaca", "language learning"), ", ",
    a("https://github.com/cstuartroe/storyweb", "creative writing"), ", ",
    "music ",
    a("https://github.com/cstuartroe/notesy", "performance"),
    " and ",
    a("https://github.com/cstuartroe/scale-theory", "composition"), ", ",
    a("https://github.com/cstuartroe/svg_gen", "visual art"), ", ",
    a("https://github.com/cstuartroe/celestial-cards", "tabletop games"), ", ",
    "and of course ",
    a("https://github.com/cstuartroe/lauvinko", "conlanging"), ", ",
    a("https://github.com/cstuartroe/kuna", "conlanging"), ", ",
    a("https://github.com/cstuartroe/jaobon", "conlanging"), "). ",
    "So naturally, when I picked Jaobon back up in April 2023 my first act was to ",
    a("https://github.com/cstuartroe/jaobon/commit/636da35dc303a9fa14424863a2de970288f6e4bc", "digitize it"), " ",
    "and put it online.",
  ),
  p(
    "Soon after, I ",
    a("https://github.com/cstuartroe/jaobon/commit/e2d57ae5e92c52b7c70899adb314e8287c4b4d6c", "zipped up all the gaps"), " ",
    "and brought the language to 350 morphemes, occupying every permissible syllable.",
  ),
  p(
    "In April 2024 I finally ",
    a("https://github.com/cstuartroe/jaobon/commit/a4ee704eaa1f50b2645a3403b413c243a2628f1", "wrote out"), " ",
    "a reasonably comprehensive description of Jaobon grammar.",
  ),
  p(
    "In January 2025 I ",
    a("https://github.com/cstuartroe/jaobon/commit/cd46ad4b49e74d2ff15d3c5a77aed8247e7b92d0", "changed Jaobon phonology"), " ",
    "for the first time since 2019 and only the second time ever, adding the diphthong ",
    ipa("/oi̯/"), ", ",
    "bringing the total number of possible syllables to 366 and filling all the vacant real estate with new roots. ",
    "This was partially motivated by wanting to ",
    a("https://bsky.app/profile/jaobon.bsky.social", "associate each calendar day"), " ",
    "with a Jaobon root (I'm also into calendrics), and partially motivated by still feeling a bit cramped. ",
    "Crazy as it may seem, that bump up from 350 to 366 roots felt like it was really hitting the sweet spot. ",
    "I finally got to de-conflate terms for emotion and color, something which I'd found undesirable for a ",
    "long time (previously, e.g. \"blue\" and \"sad\" were the same term), and added a few nice new roots that felt needed. ",
    "For the first time in Jaobon's history, I really feel like every root has semantic breathing room and there ",
    "are no gaps nor any ideas that are challenging to express. ",
    "There's also been a steep reduction in seriously phonetically mangled etymologies. ",
  ),
  p(
    "Now Jaobon has a dictionary exceeding 1000 entries and a corpus of translations exceeding 8000 roots, ",
    "and is finally feeling like a mature, convincing, and presentable project. ",
    "I think I accomplished the original goal of finding the number of roots that makes an oligoanalytic ",
    "language \"click\" for me - where any fewer would feel cramped, but where I can't think of any root I'd like ",
    "to add or split up. ",
  ),
];

export default function History(props: {}) {
  return documentToJSX(HistoryDocument);
}
