import { validSyllableString } from "./syllables";

type SourceLanguage = "Mandarin" | "Spanish" | "English" | "Arabic" | "Polish" | "Latin" | "French" | "Turkish" | "Dutch" | "Japanese" | "Hindi" | "Malay" | "Russian" | "German";

type Etymology = {
    language: SourceLanguage,
    word: string,
}

type Root = {
    definition: string,
    etymologies: Etymology[],
    CJK: string,
}

const usedCJK = new Set<string>();

function root(syll: string, definition: string, CJK: string, etymologies: [SourceLanguage, string][]): [string, Root] {
    if (!validSyllableString(syll)) {
        throw `Invalid syllable: ${syll}`
    }
    if (CJK.length != 1) {
        throw `Invalid CJK: ${CJK}`
    }
    if (usedCJK.has(CJK)) {
        throw `Duplicate CJK: ${CJK}`
    }
    usedCJK.add(CJK);
    return [
        syll,
        {
            definition,
            CJK,
            etymologies: etymologies.map(([language, word], _) => ({language, word})),
        },
    ];
}

export const ROOTS = new Map<string, Root>([
    root(
        "a",
        "to, toward, at, for",
        "向",
        [["Spanish", "a"]],
    ),
    root(
        "ai",
        "love",
        "爱",
        [["Mandarin", "爱"]],
    ),
    root(
        "ak",
        "act, behave, appear, seem, express",
        "表",
        [["English", "act"]],
    ),
    root(
        "an",
        "animal, beast",
        "兽",
        [["English", "animal"], ["Spanish", "animal"]],
    ),
    root(
        "ao",
        "strange, unknown, mysterious",
        "奥",
        [["Mandarin", "奥"]],
    ),
    root(
        "as",
        "make, cause, volitive",
        "使",
        [["Spanish", "hacer"]],
    ),
    root(
        "ba",
        "hold, wield, handle",
        "把",
        [["Mandarin", "把"]],
    ),
    root(
        "bai",
        "hundred",
        "百",
        [["Mandarin", "百"]],
    ),
    root(
        "bak",
        "cow, bovine",
        "牛",
        [["Spanish", "vaca"]],
    ),
    root(
        "ban",
        "half",
        "半",
        [["Mandarin", "半"]],
    ),
    root(
        "bao",
        "bag, package, bundle; to cover, to wrap",
        "包",
        [["Mandarin", "包"]],
    ),
    root(
        "bas",
        "empty, blank, vacant, hollow",
        "空",
        [["Spanish", "vacío"]],
    ),
    root(
        "be",
        "beautiful, nice",
        "美",
        [["Spanish", "bello"]],
    ),
    root(
        "bek",
        "back, behind, after",
        "后",
        [["English", "back"]],
    ),
    root(
        "ben",
        "bend, change, become",
        "变",
        [["Mandarin", "变"], ["English", "bend"]],
    ),
    root(
        "bes",
        "time, instance, action, turn, once",
        "次",
        [["Spanish", "vez"]],
    ),
    root(
        "bi",
        "live, reside, life",
        "活",
        [["Spanish", "vivir"]],
    ),
    root(
        "bik",
        "big, large, old",
        "大",
        [["English", "big"]],
    ),
    root(
        "bin",
        "freeze, cold",
        "冰",
        [["Mandarin", "冰"]],
    ),
    root(
        "bis",
        "visit, travel, tour, guest",
        "客",
        [["Spanish", "visitar"], ["English", "visit"]],
    ),
    root(
        "bo",
        "fly",
        "飞",
        [["Spanish", "volar"]],
    ),
    root(
        "bok",
        "mouth, hole open at one end",
        "孔",
        [["Spanish", "boca"]],
    ),
    root(
        "bon",
        "under, bottom, bum",
        "下",
        [["English", "bottom"], ["Mandarin", "本"]],
    ),
    root(
        "bos",
        "voice, sound, noise, make noise",
        "声",
        [["Spanish", "voz"]],
    ),
    root(
        "bu",
        "section, department",
        "部",
        [["Mandarin", "部"]],
    ),
    root(
        "buk",
        "book",
        "书",
        [["English", "book"]],
    ),
    root(
        "bun",
        "boon, prize, accomplishment, asset",
        "财",
        [["English", "boon"]],
    ),
    root(
        "bus",
        "seek, search, look for, want, aim, goal",
        "找",
        [["Spanish", "buscar"]],
    ),
    root(
        "ca",
        "fall short, difference, minus, mistake, break, error, bad",
        "差",
        [["Mandarin", "差"]],
    ),
    root(
        "cai",
        "boil, tea",
        "茶",
        [["Mandarin", "茶"]],
    ),
    root(
        "cak",
        "sing, praise",
        "歌",
        [["Mandarin", "唱歌"]],
    ),
    root(
        "can",
        "wall, barrier, block",
        "墙",
        [["Mandarin", "墙"]],
    ),
    root(
        "cao",
        "long, string, strip, ribbon, extreme",
        "条",
        [["Mandarin", "条"], ["Mandarin", "超"]],
    ),
    root(
        "cas",
        "click, snap, pop",
        "咔",
        [["Spanish", "chasquear"]],
    ),
    root(
        "ce",
        "car, vehicle",
        "车",
        [["Mandarin", "車"]],
    ),
    root(
        "cek",
        "(diminutive suffix)",
        "子",
        [["Polish", "-czek"]],
    ),
    root(
        "cen",
        "front, face, before",
        "前",
        [["Mandarin", "前"]],
    ),
    root(
        "ces",
        "chase, pursue, follow",
        "追",
        [["English", "chase"]],
    ),
    root(
        "ci",
        "seven",
        "七",
        [["Mandarin", "七"]],
    ),
    root(
        "cik",
        "fowl, chicken",
        "鸡",
        [["English", "chicken"]],
    ),
    root(
        "cin",
        "polite, please, customary",
        "请",
        [["Mandarin", "请"]],
    ),
    root(
        "cis",
        "cheese, form, coagulate, curdle",
        "酪",
        [["English", "cheese"]],
    ),
    root(
        "co",
        "eat, drink, consume",
        "吃",
        [["Mandarin", "吃"]],
    ),
    root(
        "cok",
        "ball, sphere",
        "球",
        [["Mandarin", "球体"]],
    ),
    root(
        "con",
        "insect, worm",
        "虫",
        [["Mandarin", "虫"]],
    ),
    root(
        "cos",
        "trust, believe in, faith, confidence",
        "信",
        [["English", "trust"]],
    ),
    root(
        "cu",
        "out, send, happen, leave, quit, depart",
        "出",
        [["Mandarin", "出"]],
    ),
    root(
        "cuk",
        "store, stockpile, preserve, save, keep",
        "储",
        [["Mandarin", "储备"], ["Mandarin", "储存"]],
    ),
    root(
        "cun",
        "vitality, life, lust, spring, alive",
        "春",
        [["Mandarin", "春"]],
    ),
    root(
        "cus",
        "choose, select",
        "选",
        [["English", "choose"]],
    ),
    root(
        "da",
        "hit, strike",
        "打",
        [["Mandarin", "打"]],
    ),
    root(
        "dai",
        "support, carry, bring",
        "带",
        [["Mandarin", "带"]],
    ),
    root(
        "dak",
        "dark, black",
        "黑",
        [["English", "dark"]],
    ),
    root(
        "dan",
        "simple, easy",
        "单",
        [["Mandarin", "单"]],
    ),
    root(
        "dao",
        "road, way, path, direction, go, arrive",
        "道",
        [["Mandarin", "道"], ["Mandarin", "到"]],
    ),
    root(
        "das",
        "ten",
        "十",
        [["Hindi", "दस"]],
    ),
    root(
        "de",
        "from, off of, away from",
        "从",
        [["Spanish", "de"]],
    ),
    root(
        "dek",
        "thin, slender",
        "细",
        [["Spanish", "delgado"]],
    ),
    root(
        "den",
        "inside",
        "内",
        [["Spanish", "dentro"]],
    ),
    root(
        "des",
        "speak, say, mean, signify",
        "言",
        [["Spanish", "decir"]],
    ),
    root(
        "do",
        "sleep",
        "睡",
        [["Spanish", "dormir"]],
    ),
    root(
        "dok",
        "dog",
        "犬",
        [["English", "dog"]],
    ),
    root(
        "don",
        "understand; east",
        "懂",
        [["Mandarin", "東"], ["Mandarin", "懂"]],
    ),
    root(
        "dos",
        "two, pair",
        "二",
        [["Spanish", "dos"]],
    ),
    root(
        "du",
        "belly, stomach",
        "肚",
        [["Mandarin", "肚"]],
    ),
    root(
        "dus",
        "city",
        "市",
        [["Mandarin", "都市"]],
    ),
    root(
        "dun",
        "shield, guard, cover",
        "盾",
        [["Mandarin", "盾"]],
    ),
    root(
        "duk",
        "hard, strong, tough, stiff",
        "刚",
        [["Spanish", "duro"]],
    ),
    root(
        "e",
        "hungry, greedy, starve",
        "饿",
        [["Mandarin", "饿"]],
    ),
    root(
        "ek",
        "far, distant, foreign, outside, apart",
        "外",
        [["English", "ex-"], ["Spanish", "ex-"]],
    ),
    root(
        "en",
        "in, on, continuous",
        "在",
        [["Spanish", "en"]],
    ),
    root(
        "es",
        "be, absolutive",
        "是",
        [["Spanish", "es"], ["Spanish", "estar"]],
    ),
    root(
        "ga",
        "gather, assemble, condense, aggregate",
        "集",
        [["English", "gather"]],
    ),
    root(
        "gai",
        "should, ought",
        "该",
        [["Mandarin", "该"]],
    ),
    root(
        "gak",
        "cat",
        "猫",
        [["Spanish", "gato"]],
    ),
    root(
        "gan",
        "win, gain",
        "赢",
        [["Spanish", "ganar"]],
    ),
    root(
        "gao",
        "tall, high, noble",
        "高",
        [["Mandarin", "高"]],
    ),
    root(
        "gas",
        "gas, air, smell, weather",
        "气",
        [["English", "gas"], ["Spanish", "gas"]],
    ),
    root(
        "ge",
        "give, offer",
        "给",
        [["Mandarin", "给"]],
    ),
    root(
        "gek",
        "get, receive",
        "收",
        [["English", "get"]],
    ),
    root(
        "gen",
        "root, source, origin",
        "根",
        [["Mandarin", "根"]],
    ),
    root(
        "ges",
        "rule, law",
        "规",
        [["Mandarin", "规则"]],
    ),
    root(
        "gi",
        "guide, steer, direct, lead, govern",
        "导",
        [["Spanish", "guiar"]],
    ),
    root(
        "gik",
        "geek, enthusiast",
        "迷",
        [["English", "geek"]],
    ),
    root(
        "gis",
        "hide, conceal, obscure, secret",
        "秘",
        [["Turkish", "giz"], ["Turkish", "gizlemek"]],
    ),
    root(
        "gin",
        "green",
        "绿",
        [["English", "green"]],
    ),
    root(
        "go",
        "enough, adequate, suffice",
        "够",
        [["Mandarin", "够"]],
    ),
    root(
        "gok",
        "drop, bead, spot, point, grain",
        "点",
        [["Spanish", "gota"]],
    ),
    root(
        "gon",
        "public, shared, government",
        "公",
        [["Mandarin", "公"], ["Mandarin", "共"]],
    ),
    root(
        "gos",
        "fruit, egg, produce, results",
        "果",
        [["Mandarin", "果实"]],
    ),
    root(
        "gu",
        "old, tradition, ancient, story",
        "故",
        [["Mandarin", "故"]],
    ),
    root(
        "guk",
        "group",
        "组",
        [["English", "group"], ["Spanish", "grupo"]],
    ),
    root(
        "gun",
        "stick, tube, pipe",
        "管",
        [["Mandarin", "管"]],
    ),
    root(
        "gus",
        "story, narrative, matter",
        "事",
        [["Mandarin", "故事"]],
    ),
    root(
        "ha",
        "laugh",
        "哈",
        [["Mandarin", "哈哈"], ["English", "haha"], ["Spanish", "jaja"]],
    ),
    root(
        "hai",
        "still, yet, additional, surplus, also",
        "还",
        [["Mandarin", "还"]],
    ),
    root(
        "hak",
        "heart, emotion, feel, center",
        "心",
        [["English", "heart"]],
    ),
    root(
        "han",
        "reverse, opposite, against, return, respond, react",
        "反",
        [["Mandarin", "返"], ["Mandarin", "反"]],
    ),
    root(
        "hao",
        "good, beneficial, pleasant, beautiful, just",
        "好",
        [["Mandarin", "好"]],
    ),
    root(
        "has",
        "up to, until",
        "至",
        [["Spanish", "hasta"]],
    ),
    root(
        "he",
        "heal, health, healthy",
        "健",
        [["English", "health"]],
    ),
    root(
        "hek",
        "hate, be disgusted by",
        "恨",
        [["English", "hate"]],
    ),
    root(
        "hen",
        "very",
        "很",
        [["Mandarin", "很"]],
    ),
    root(
        "hes",
        "breathe, smell",
        "吸",
        [["Spanish", "respirar"], ["Mandarin", "呼吸"]],
    ),
    root(
        "ho",
        "thick, ample, deep, wide, dense, fat",
        "厚",
        [["Mandarin", "厚"]],
    ),
    root(
        "hok",
        "hot, heat",
        "热",
        [["English", "hot"]],
    ),
    root(
        "hon",
        "red, anger, passion",
        "红",
        [["Mandarin", "红"]],
    ),
    root(
        "hos",
        "horse, equine",
        "马",
        [["English", "horse"]],
    ),
    root(
        "hu",
        "game, play, have fun",
        "玩",
        [["Spanish", "jugar"]],
    ),
    root(
        "huk",
        "hook, bend, curve, corner",
        "角",
        [["English", "hook"]],
    ),
    root(
        "hun",
        "mix, mingle, together, marriage",
        "混",
        [["Mandarin", "混"], ["Spanish", "junto"], ["Mandarin",  "婚"]],
    ),
    root(
        "hus",
        "monkey, ape",
        "猴",
        [["Mandarin", "猴子"]],
    ),
    root(
        "i",
        "and, also, add, again",
        "又",
        [["Spanish", "y"]],
    ),
    root(
        "ik",
        "child, offshoot",
        "儿",
        [["Spanish", "hijo"]],
    ),
    root(
        "in",
        "pull, stretch, extend",
        "引",
        [["Mandarin", "引"]],
    ),
    root(
        "is",
        "left",
        "左",
        [["Spanish", "izquierdo"]],
    ),
    root(
        "ja",
        "family, household",
        "家",
        [["Mandarin", "家"]],
    ),
    root(
        "jai",
        "victory, glory, long live",
        "胜",
        [["Hindi", "जय"]],
    ),
    root(
        "jak",
        "coat, jacket",
        "袄",
        [["English", "jacket"]],
    ),
    root(
        "jan",
        "flat, straight, correct, right, proper, stand",
        "长",
        [["Mandarin", "张"], ["Mandarin", "长"], ["Mandarin", "站"]],
    ),
    root(
        "jao",
        "foot, leg",
        "脚",
        [["Mandarin", "脚"]],
    ),
    root(
        "jas",
        "true, real, genuine, serious",
        "真",
        [["Mandarin", "真实"]],
    ),
    root(
        "je",
        "this, that",
        "这",
        [["Mandarin", "这"]],
    ),
    root(
        "jek",
        "think, believe, feel",
        "觉",
        [["Mandarin", "觉得"]],
    ),
    root(
        "jen",
        "person, human",
        "人",
        [["Mandarin", "人"]],
    ),
    root(
        "jes",
        "introduce, bring up, advise, comment, suggest",
        "介",
        [["Mandarin", "介紹"], ["English", "suggest"]],
    ),
    root(
        "ji",
        "number, amount, how many, some, ordinal, unit, count",
        "计",
        [["Mandarin", "几"], ["Mandarin", "计"], ["Mandarin", "第"]],
    ),
    root(
        "jik",
        "structure, organization, institution",
        "机",
        [["Mandarin", "机关"], ["Mandarin", "机构"]],
    ),
    root(
        "jin",
        "yellow, brown, gold, metal, money",
        "金",
        [["Mandarin", "金"]],
    ),
    root(
        "jis",
        "skill, craft, technology, technique, art",
        "术",
        [["Mandarin", "技术"]],
    ),
    root(
        "jo",
        "just, only, already, as soon as",
        "就",
        [["Mandarin", "就"]],
    ),
    root(
        "jok",
        "humor, joke",
        "逗",
        [["English", "joke"]],
    ),
    root(
        "jon",
        "seed, bean, gamete, gene, sexual, species",
        "种",
        [["Mandarin", "种"]],
    ),
    root(
        "jos",
        "table, desk",
        "桌",
        [["Mandarin", "桌子"]],
    ),
    root(
        "ju",
        "tree, plant",
        "株",
        [["Mandarin", "株"], ["Mandarin", "植物"]],
    ),
    root(
        "juk",
        "if",
        "如",
        [["Mandarin", "如果"]],
    ),
    root(
        "jun",
        "bacteria, mold",
        "菌",
        [["Mandarin", "菌"]],
    ),
    root(
        "jus",
        "juice, liquid, blood",
        "汁",
        [["English", "juice"]],
    ),
    root(
        "ka",
        "fall, drop, down",
        "跌",
        [["Spanish", "caer"]],
    ),
    root(
        "kai",
        "start, open, begin, operate",
        "开",
        [["Mandarin", "开"]],
    ),
    root(
        "kak",
        "feces",
        "屎",
        [["Spanish", "caca"]],
    ),
    root(
        "kan",
        "see, read",
        "看",
        [["Mandarin", "看"]],
    ),
    root(
        "kao",
        "test, inspect, consider, try",
        "考",
        [["Mandarin", "考"]],
    ),
    root(
        "kas",
        "house, home, building",
        "房",
        [["Spanish", "casa"]],
    ),
    root(
        "ke",
        "what, which",
        "何",
        [["Spanish", "qué"]],
    ),
    root(
        "kek",
        "sibling",
        "兄",
        [["Malay", "kakak"], ["Arabic", "شقيق"]],
    ),
    root(
        "ken",
        "can, may, possible, able",
        "能",
        [["English", "can"], ["Mandarin", "可能"]],
    ),
    root(
        "kes",
        "grow, increase",
        "增",
        [["Spanish", "crecer"]],
    ),
    root(
        "ki",
        "(relativizer, complementizer)",
        "者",
        [["French", "qui"]],
    ),
    root(
        "kik",
        "remove, take away, clean off",
        "除",
        [["Spanish", "quitar"]],
    ),
    root(
        "kin",
        "keen, sharp, witty, clever, blade",
        "锐",
        [["English", "keen"]],
    ),
    root(
        "kis",
        "kiss",
        "吻",
        [["English", "kiss"]],
    ),
    root(
        "ko",
        "door, opening, hole open at both ends",
        "口",
        [["Mandarin", "口"]],
    ),
    root(
        "kok",
        "cut, separate, short, restrict",
        "刻",
        [["English", "cut"], ["Spanish", "cortar"], ["Spanish", "corto"]],
    ),
    root(
        "kon",
        "recognize, be familiar with",
        "识",
        [["Spanish", "conocer"]],
    ),
    root(
        "kos",
        "thing, object, tool",
        "物",
        [["Spanish", "cosa"]],
    ),
    root(
        "ku",
        "bitterness, suffering, unpleasantness, alkali",
        "苦",
        [["Mandarin", "苦"]],
    ),
    root(
        "kuk",
        "cook, burn, heat up",
        "烧",
        [["English", "cook"]],
    ),
    root(
        "kun",
        "fear, afraid",
        "恐",
        [["Mandarin", "恐"]],
    ),
    root(
        "kus",
        "hear",
        "听",
        [["Spanish", "escuchar"]],
    ),
    root(
        "la",
        "side, edge, direction",
        "边",
        [["Spanish", "lado"]],
    ),
    root(
        "lai",
        "come, become, exhortative",
        "来",
        [["Mandarin", "来"]],
    ),
    root(
        "lak",
        "milk",
        "奶",
        [["Latin", "lac"]],
    ),
    root(
        "lan",
        "blue, body of water, sad",
        "蓝",
        [["Mandarin", "蓝"]],
    ),
    root(
        "lao",
        "allow, let",
        "许",
        [["English", "allow"]],
    ),
    root(
        "las",
        "glass, transparent",
        "玻",
        [["English", "glass"]],
    ),
    root(
        "le",
        "type, kind, class",
        "类",
        [["Mandarin", "类"]],
    ),
    root(
        "lek",
        "electric, electricity",
        "电",
        [["English", "electric"], ["Spanish", "eléctrico"]],
    ),
    root(
        "len",
        "slow",
        "慢",
        [["Spanish", "lento"]],
    ),
    root(
        "les",
        "read, understand, interpret, study",
        "读",
        [["German", "lesen"]],
    ),
    root(
        "li",
        "ritual, ceremony, etiquette, custom, gift",
        "礼",
        [["Mandarin", "礼"]],
    ),
    root(
        "lik",
        "lightweight, fragile, weak, slight, minor",
        "轻",
        [["Spanish", "ligero"]],
    ),
    root(
        "lin",
        "clean, clear",
        "洁",
        [["Spanish", "limpio"]],
    ),
    root(
        "lis",
        "ready, clever, ripe, alert",
        "备",
        [["Spanish", "listo"]],
    ),
    root(
        "lo",
        "low, short",
        "矮",
        [["English", "low"]],
    ),
    root(
        "lok",
        "crazy",
        "狂",
        [["Spanish", "loco"]],
    ),
    root(
        "lon",
        "unique, alone, solitary",
        "独",
        [["English", "lone"]],
    ),
    root(
        "los",
        "level, floor, layer, stratum",
        "层",
        [["Mandarin", "楼层"]],
    ),
    root(
        "lu",
        "flow, pour, spill, move, circulate",
        "流",
        [["Mandarin", "流"], ["Spanish", "fluir"]],
    ),
    root(
        "luk",
        "place, location",
        "所",
        [["Spanish", "lugar"]],
    ),
    root(
        "lun",
        "round, circle, wheel, cycle",
        "轮",
        [["Mandarin", "轮"]],
    ),
    root(
        "lus",
        "light, intelligence, clarity, upbeat",
        "光",
        [["Spanish", "luz"]],
    ),
    root(
        "ma",
        "mother",
        "妈",
        [["English", "ma"], ["Spanish", "mamá"], ["Mandarin", "妈妈"]],
    ),
    root(
        "mai",
        "sell, convince",
        "卖",
        [["Mandarin", "卖"]],
    ),
    root(
        "mak",
        "make, construct, create, prepare",
        "作",
        [["English", "make"], ["Dutch", "maken"], ["German", "machen"]],
    ),
    root(
        "man",
        "full, satisfied, complete, whole, entire",
        "满",
        [["Mandarin", "满"]],
    ),
    root(
        "mao",
        "hair, fur, feather, wool, bristle",
        "毛",
        [["Mandarin", "毛"]],
    ),
    root(
        "mas",
        "more, compare, most",
        "更",
        [["Spanish", "más"]],
    ),
    root(
        "me",
        "all, each, every",
        "每",
        [["Mandarin", "每"]],
    ),
    root(
        "mek",
        "mechanism, device, tool, machine, contraption",
        "器",
        [["English", "mechanism"], ["Spanish", "mecanismo"]],
    ),
    root(
        "men",
        "plural, many, much, a lot",
        "们",
        [["English", "many"], ["Mandarin", "们"]],
    ),
    root(
        "mes",
        "middle, center, between, among",
        "中",
        [["English", "meso-"], ["Spanish", "medio"]],
    ),
    root(
        "mi",
        "1st person",
        "我",
        [["English", "me"], ["Spanish", "mí"]],
    ),
    root(
        "mik",
        "friend, kind, amicable",
        "友",
        [["Spanish", "amigo"]],
    ),
    root(
        "min",
        "name, word, call, refer",
        "名",
        [["Mandarin", "名"]],
    ),
    root(
        "mis",
        "miss, err, mistake",
        "失",
        [["English", "miss"], ["English", "mistake"]],
    ),
    root(
        "mo",
        "die, stop, halt, pause, end",
        "末",
        [["Spanish", "morir"], ["Mandarin", "末"]],
    ),
    root(
        "mok",
        "nag, annoy, bother, harass, disturb",
        "烦",
        [["Spanish", "molestar"]],
    ),
    root(
        "mon",
        "mountain, hill, mound, pile, heap, mass",
        "山",
        [["English", "mound"], ["English", "mountain"], ["Spanish", "montón"], ["Spanish", "montaña"]],
    ),
    root(
        "mos",
        "must, have to (epistemic and deontic senses)",
        "必",
        [["English", "must"]],
    ),
    root(
        "mu",
        "tree, post, column, wood",
        "木",
        [["Mandarin", "木"]],
    ),
    root(
        "muk",
        "free, open, unencumbered, loose, relaxed",
        "放",
        [["Hindi", "मुक्त"]],
    ),
    root(
        "mun",
        "moon, month",
        "月",
        [["English", "moon"]],
    ),
    root(
        "mus",
        "mouse, rodent",
        "鼠",
        [["English", "mouse"], ["Latin", "mūs"]],
    ),
    root(
        "na",
        "swim",
        "泳",
        [["Spanish", "nadar"]],
    ),
    root(
        "nai",
        "nine",
        "九",
        [["English", "nine"]],
    ),
    root(
        "nak",
        "nature, character, base, bare, naked",
        "露",
        [["Spanish", "natural"], ["English", "natural"], ["English", "naked"]],
    ),
    root(
        "nan",
        "male, masculine; south",
        "男",
        [["Mandarin", "男"], ["Mandarin", "南"]],
    ),
    root(
        "nao",
        "brain, mind",
        "脑",
        [["Mandarin", "脑"]],
    ),
    root(
        "nas",
        "nation, people, ethnicity",
        "国",
        [["English", "nation"], ["Spanish", "nación"]],
    ),
    root(
        "ne",
        "system, network, economy, environment, internet",
        "网",
        [["English", "net"]],
    ),
    root(
        "nek",
        "neck, stem",
        "颈",
        [["English", "neck"]],
    ),
    root(
        "nen",
        "year",
        "年",
        [["Mandarin", "年"]],
    ),
    root(
        "nes",
        "essence, abstract noun",
        "性",
        [["English", "-ness"]],
    ),
    root(
        "ni",
        "2nd person",
        "你",
        [["Mandarin", "你"]],
    ),
    root(
        "nik",
        "meat, flesh, organ",
        "肉",
        [["Japanese", "肉"]],
    ),
    root(
        "nin",
        "none, nothing, zero",
        "无",
        [["Spanish", "ninguno"]],
    ),
    root(
        "nis",
        "about, concerning, with regard to",
        "关",
        [["Japanese", "について"]],
    ),
    root(
        "no",
        "no, not",
        "不",
        [["English", "no"], ["Spanish", "no"]],
    ),
    root(
        "nok",
        "night; north",
        "夕",
        [["Spanish", "noche"], ["Spanish", "norte"], ["English", "north"]],
    ),
    root(
        "non",
        "farm, grow, raise, agriculture",
        "农",
        [["Mandarin", "农"]],
    ),
    root(
        "nos",
        "nose",
        "鼻",
        [["English", "nose"]],
    ),
    root(
        "nu",
        "new, young",
        "新",
        [["English", "new"]],
    ),
    root(
        "nun",
        "noon, daytime",
        "午",
        [["English", "noon"]],
    ),
    root(
        "nus",
        "feminine, female",
        "女",
        [["Mandarin", "女性"]],
    ),
    root(
        "nuk",
        "nut, bead",
        "珠",
        [["Latin", "nux"]],
    ),
    root(
        "o",
        "or, other",
        "另",
        [["Spanish", "or"], ["Spanish", "otro"]],
    ),
    root(
        "ok",
        "eight",
        "八",
        [["Spanish", "ocho"]],
    ),
    root(
        "on",
        "fungus, mushroom",
        "菇",
        [["Spanish", "hongo"]],
    ),
    root(
        "os",
        "bear",
        "熊",
        [["Spanish", "oso"]],
    ),
    root(
        "pa",
        "father",
        "父",
        [["English", "pa"], ["Spanish", "papá"]],
    ),
    root(
        "pai",
        "arrange, put in order, oversee, row",
        "排",
        [["Mandarin", "排"]],
    ),
    root(
        "pak",
        "bird",
        "鸟",
        [["Spanish", "pájaro"]],
    ),
    root(
        "pan",
        "bread, rice, starch, grain",
        "饭",
        [["Spanish", "pan"], ["Mandarin", "饭"]],
    ),
    root(
        "pao",
        "power, energy, strength",
        "力",
        [["English", "power"]],
    ),
    root(
        "pas",
        "pass, cross, across, on the other side of, experiential, spend time",
        "过",
        [["English", "pass"], ["Spanish", "pasar"]],
    ),
    root(
        "pe",
        "lose, pay, pain, suffer",
        "损",
        [["English", "pay"], ["Spanish", "perder"], ["Spanish", "pena"]],
    ),
    root(
        "pek",
        "sticky, adhere, glue, attach",
        "黏",
        [["Spanish", "pegar"]],
    ),
    root(
        "pen",
        "slice, sheet, paper, card, leaf",
        "片",
        [["Mandarin", "片"]],
    ),
    root(
        "pes",
        "weight, mass, importance, heavy",
        "重",
        [["Spanish", "peso"]],
    ),
    root(
        "pi",
        "skin, outside, edge, peel, surface",
        "皮",
        [["English", "peel"], ["Spanish", "piel"], ["Mandarin", "皮"]],
    ),
    root(
        "pik",
        "picture, image, depiction, explanation",
        "像",
        [["English", "picture"]],
    ),
    root(
        "pin",
        "pin, needle, point, prick, pen",
        "针",
        [["English", "pin"], ["Spanish", "pinchar"]],
    ),
    root(
        "pis",
        "piece, part, drop, singulative",
        "块",
        [["English", "piece"], ["Spanish", "pieza"]],
    ),
    root(
        "po",
        "poor, helpless, forlorn, meager, sparse, few, scarce",
        "乏",
        [["English", "poor"], ["Spanish", "pobre"], ["Spanish", "poco"]],
    ),
    root(
        "pok",
        "pig",
        "猪",
        [["Spanish", "puerco"]],
    ),
    root(
        "pon",
        "put, place, add, set",
        "加",
        [["Spanish", "poner"]],
    ),
    root(
        "pos",
        "position, role, place, status",
        "位",
        [["English", "position"], ["Spanish", "puesto"], ["Spanish", "posición"]],
    ),
    root(
        "pu",
        "four",
        "四",
        [["English", "four"]],
    ),
    root(
        "puk",
        "conflict, fight, war",
        "争",
        [["Spanish", "pugnar"]],
    ),
    root(
        "pun",
        "fundamental, basic, basis",
        "基",
        [["Spanish", "fundamental"], ["English", "fundamental"]],
    ),
    root(
        "pus",
        "complex, difficult",
        "复",
        [["Mandarin", "复杂"]],
    ),
    root(
        "sa",
        "know",
        "知",
        [["Spanish", "saber"]],
    ),
    root(
        "sai",
        "vegetable, plant",
        "菜",
        [["Mandarin", "菜"]],
    ),
    root(
        "sak",
        "alcohol",
        "酒",
        [["Japanese", "酒"]],
    ),
    root(
        "san",
        "three",
        "三",
        [["Mandarin", "三"]],
    ),
    root(
        "sao",
        "early, morning",
        "早",
        [["Mandarin", "早"]],
    ),
    root(
        "sas",
        "sauce, dressing",
        "酱",
        [["English", "sauce"], ["Spanish", "salsa"]],
    ),
    root(
        "se",
        "self, reflexive",
        "己",
        [["Spanish", "se"]],
    ),
    root(
        "sek",
        "dry, thirsty",
        "干",
        [["Spanish", "seco"]],
    ),
    root(
        "sen",
        "sit, stay, remain, continue",
        "坐",
        [["Spanish", "sentar"]],
    ),
    root(
        "ses",
        "six",
        "六",
        [["Spanish", "seis"]],
    ),
    root(
        "so",
        "color",
        "色",
        [["Mandarin", "色"]],
    ),
    root(
        "sok",
        "lock, latch, secure",
        "锁",
        [["Mandarin", "锁定"], ["English", "secure"]],
    ),
    root(
        "son",
        "sun, day",
        "日",
        [["English", "sun"]],
    ),
    root(
        "sos",
        "social, society",
        "交",
        [["English", "social"], ["English", "society"], ["Spanish", "social"], ["Spanish", "sociedad"]],
    ),
    root(
        "su",
        "fast, quick",
        "速",
        [["Mandarin", "速"]],
    ),
    root(
        "suk",
        "sugar",
        "糖",
        [["Spanish", "azúcar"]],
    ),
    root(
        "sun",
        "sour, acid",
        "酸",
        [["Mandarin", "酸"]],
    ),
    root(
        "sus",
        "dirty, gross, grubby, unwashed",
        "污",
        [["Spanish", "sucio"]],
    ),
    root(
        "ta",
        "3rd person, thing",
        "他",
        [["Mandarin", "他"], ["Mandarin", "她"], ["Mandarin", "它"]],
    ),
    root(
        "tai",
        "knot, tie, join, connect, relate",
        "系",
        [["English", "tie"]],
    ),
    root(
        "tak",
        "arm, branch, split, fork",
        "支",
        [["Dutch", "tak"]],
    ),
    root(
        "tan",
        "lie, recline",
        "躺",
        [["Mandarin", "躺"]],
    ),
    root(
        "tao",
        "thousand",
        "千",
        [["English", "thousand"]],
    ),
    root(
        "tas",
        "cup, bowl",
        "杯",
        [["Spanish", "taza"]],
    ),
    root(
        "te",
        "fabric, cloth, clothing",
        "布",
        [["Spanish", "tela"]],
    ),
    root(
        "tek",
        "take, buy",
        "拿",
        [["English", "take"]],
    ),
    root(
        "ten",
        "sky, heaven, god, holy, sacred",
        "天",
        [["Mandarin", "天"]],
    ),
    root(
        "tes",
        "taste, smell, flavor, preference",
        "味",
        [["English", "taste"]],
    ),
    root(
        "to",
        "head, individual, chief",
        "头",
        [["Mandarin", "头"]],
    ),
    root(
        "tok",
        "touch, feel, play (instrument)",
        "着",
        [["Spanish", "tocar"]],
    ),
    root(
        "ton",
        "same, common, like, as",
        "同",
        [["Mandarin", "同"]],
    ),
    root(
        "tos",
        "throw, throw out, reject, expel, emit, spew, cough",
        "扔",
        [["English", "toss"], ["Spanish", "tos"]],
    ),
    root(
        "tu",
        "ground, land, dirt, territory, earth",
        "土",
        [["Mandarin", "土"]],
    ),
    root(
        "tuk",
        "body, corpse, torso, person",
        "身",
        [["Russian", "труп"], ["Mandarin", "tubuh"]],
    ),
    root(
        "tun",
        "music, harmony",
        "乐",
        [["English", "tune"]],
    ),
    root(
        "tus",
        "paint, smear, wipe, coating, layer",
        "涂",
        [["Mandarin", "涂层"], ["Mandarin", "涂饰"]],
    ),
    root(
        "u",
        "five",
        "五",
        [["Mandarin", "五"]],
    ),
    root(
        "uk",
        "dance",
        "舞",
        [["Mandarin", "舞蹈"]],
    ),
    root(
        "un",
        "one, a, some, any",
        "一",
        [["Spanish", "un"], ["Spanish", "uno"]],
    ),
    root(
        "us",
        "substance, material, matter",
        "质",
        [["Mandarin", "物质"]],
    ),
    root(
        "wa",
        "water, liquid",
        "水",
        [["English", "water"], ["Spanish", "agua"]],
    ),
    root(
        "wai",
        "white, pale",
        "白",
        [["English", "white"]],
    ),
    root(
        "wak",
        "walk, move",
        "走",
        [["English", "walk"]],
    ),
    root(
        "wan",
        "late, night, evening",
        "晚",
        [["Mandarin", "晚"]],
    ),
    root(
        "wao",
        "wow, (exclamation)",
        "哇",
        [["English", "wow"]],
    ),
    root(
        "was",
        "wash",
        "洗",
        [["English", "wash"]],
    ),
    root(
        "we",
        "way, state, manner, function, reason, in order to",
        "为",
        [["English", "way"], ["Mandarin", "为"]],
    ),
    root(
        "wek",
        "alert, awake, wait, anticipate",
        "醒",
        [["English", "wake"], ["English", "wait"]],
    ),
    root(
        "wen",
        "soft, tender, mild, smooth, easy, warm",
        "温",
        [["Mandarin", "温"]],
    ),
    root(
        "wes",
        "bone; west",
        "骨",
        [["English", "west"], ["Spanish", "hueso"]],
    ),
    root(
        "wi",
        "escape, avoid, flee",
        "逃",
        [["Spanish", "huir"]],
    ),
    root(
        "wik",
        "weak, tired",
        "弱",
        [["English", "weak"]],
    ),
    root(
        "win",
        "wind, atmosphere",
        "风",
        [["English", "wind"]],
    ),
    root(
        "wis",
        "follow, with, in accompaniment",
        "跟",
        [["English", "with"]],
    ),
    root(
        "wo",
        "fire",
        "火",
        [["Mandarin", "火"]],
    ),
    root(
        "wok",
        "work, labor, position, role",
        "工",
        [["English", "work"]],
    ),
    root(
        "won",
        "ask, request, problem, issue",
        "问",
        [["Mandarin", "问"]],
    ),
    root(
        "wos",
        "worsen, decay, decline, rot, deteriorate",
        "朽",
        [["English", "worsen"], ["Malay", "rosot"], ["Malay", "rosak"]],
    ),
    root(
        "xa",
        "sand, powder",
        "沙",
        [["Mandarin", "沙"]],
    ),
    root(
        "xas",
        "time, hour",
        "时",
        [["Mandarin", "时间"], ["Mandarin", "小时"]],
    ),
    root(
        "xai",
        "shy, timid, meek, ashamed",
        "羞",
        [["English", "shy"]],
    ),
    root(
        "xak",
        "shut, closed",
        "闭",
        [["English", "shut"]],
    ),
    root(
        "xan",
        "top, over, above, up",
        "上",
        [["Mandarin", "上"]],
    ),
    root(
        "xao",
        "small, young",
        "小",
        [["Mandarin", "小"]],
    ),
    root(
        "xe",
        "write",
        "写",
        [["Mandarin", "写"]],
    ),
    root(
        "xek",
        "shake, vibrate, sway, move (back and forth)",
        "摇",
        [["English", "shake"]],
    ),
    root(
        "xen",
        "deep, rich, saturated",
        "深",
        [["Mandarin", "深"]],
    ),
    root(
        "xes",
        "learn, study",
        "学",
        [["Mandarin", "学习"]],
    ),
    root(
        "xi",
        "happy, pleased, enjoy, interest",
        "喜",
        [["Mandarin", "喜"]],
    ),
    root(
        "xik",
        "chic, hip, cool",
        "雅",
        [["French", "chic"]],
    ),
    root(
        "xin",
        "star, week",
        "星",
        [["Mandarin", "星"]],
    ),
    root(
        "xis",
        "lizard, snake, reptile",
        "蜥",
        [["Mandarin", "蜥形纲"]],
    ),
    root(
        "xo",
        "hand, arm",
        "手",
        [["Mandarin", "手"]],
    ),
    root(
        "xok",
        "stone, rock",
        "石",
        [["Mandarin", "石头"], ["English", "rock"]],
    ),
    root(
        "xon",
        "chest, breast",
        "胸",
        [["Mandarin", "胸"]],
    ),
    root(
        "xos",
        "rest, pause",
        "休",
        [["Mandarin", "休息"]],
    ),
    root(
        "xu",
        "shoe",
        "鞋",
        [["English", "shoe"]],
    ),
    root(
        "xuk",
        "thank",
        "谢",
        [["Arabic", "شكرا"]],
    ),
    root(
        "xun",
        "obey",
        "顺",
        [["Mandarin", "顺"]],
    ),
    root(
        "xus",
        "comfortable, cozy, snug, relax",
        "舒",
        [["Mandarin", "舒适"]],
    ),
    root(
        "ya",
        "press, push, control, print",
        "压",
        [["Mandarin", "压"]],
    ),
    root(
        "yai",
        "surprised, amazed",
        "讶",
        [["Mandarin", "讶异"]],
    ),
    root(
        "yak",
        "around, near, about, approximately",
        "约",
        [["Turkish", "yakın"], ["Japanese", "約"]],
    ),
    root(
        "yan",
        "sheep, goat",
        "羊",
        [["Mandarin", "羊"]],
    ),
    root(
        "yao",
        "want, need",
        "要",
        [["Mandarin", "要"]],
    ),
    root(
        "yas",
        "tooth",
        "牙",
        [["Mandarin", "牙齿"]],
    ),
    root(
        "ye",
        "also, too",
        "也",
        [["Mandarin", "也"]],
    ),
    root(
        "yek",
        "eye, personality, character, soul",
        "眼",
        [["Mandarin", "眼睛"]],
    ),
    root(
        "yen",
        "salt",
        "盐",
        [["Mandarin", "盐"]],
    ),
    root(
        "yes",
        "yes, indeed",
        "唉",
        [["English", "yes"]],
    ),
    root(
        "yo",
        "have, own, there is",
        "有",
        [["Mandarin", "有"]],
    ),
    root(
        "yok",
        "right (side)",
        "右",
        [["Mandarin", "右边"]],
    ),
    root(
        "yon",
        "leap, jump, bounce",
        "踊",
        [["Mandarin", "踊"]],
    ),
    root(
        "yos",
        "oil, fat, grease",
        "油",
        [["Mandarin", "油脂"]],
    ),
    root(
        "yu",
        "fish",
        "鱼",
        [["Mandarin", "鱼"]],
    ),
    root(
        "yuk",
        "help, assist",
        "助",
        [["Spanish", "ayudar"]],
    ),
    root(
        "yun",
        "cloud, fog, mist, steam, vapor",
        "云",
        [["Mandarin", "云"]],
    ),
    root(
        "yus",
        "use",
        "用",
        [["English", "use"]],
    ),
]);

export function sourceCounts(): Map<SourceLanguage, number> {
    const out = new Map<SourceLanguage, number>([]);

    ROOTS.forEach((root, _) => {
        const sources = new Set<SourceLanguage>([]);
        root.etymologies.forEach(e => {
            sources.add(e.language);
        });
        sources.forEach(s => {
            out.set(s, (out.get(s) || 0) + 1)
        })
    })

    return out
}
