import {validSyllableString} from "./syllables";

type SourceLanguage =
    "Chinese"
    | "Spanish"
    | "English"
    | "Arabic"
    | "Latin"
    | "French"
    | "Turkish"
    | "Dutch"
    | "Japanese"
    | "Hindi"
    | "Malay"
    | "Russian"
    | "German"
    | "Vietnamese";

export const NON_LATIN_LANGUAGES: SourceLanguage[] = ["Chinese", "Arabic", "Japanese", "Hindi", "Russian"];

type Etymology = {
    language: SourceLanguage,
    word: string,
}

export const partsOfSpeech = [
    "noun",
    "positional",
    "pronoun",
    "numeral",
    "determiner",
    "nominalizer",

    "intransitive verb",
    "adjective",
    "number particle",

    "transitive verb",
    "existential",
    "preposition",

    "adverb",
    "aspect particle",
    "voice particle",
    "coordinating conjunction",
    "subordinating conjunction",
    "relativizer",
    "linking particle",
    "interjection",
] as const;

export type PartOfSpeech = (typeof partsOfSpeech)[number];

export type Root = {
    definition: string,
    syllable: string,
    pos: PartOfSpeech[],
    etymologies: Etymology[],
    CJK: string,
    singleConsonant?: string,
}

const usedCJK = new Set<string>();

function root(syllable: string, definition: string, pos: PartOfSpeech[], CJK: string, etymologies: [SourceLanguage, string][], singleConsonant: string | undefined = undefined): [string, Root] {
    if (!validSyllableString(syllable)) {
        throw `Invalid syllable: ${syllable}`
    }
    if (CJK.length != 1) {
        throw `Invalid CJK: ${CJK}`
    }
    if (usedCJK.has(CJK)) {
        throw `Duplicate CJK: ${CJK}`
    }
    usedCJK.add(CJK);
    if (etymologies.length == 0) {
        console.log(`No etymologies: ${syllable}`);
    }
    return [
        syllable,
        {
            definition,
            syllable,
            pos,
            CJK,
            etymologies: etymologies.map(([language, word], _) => ({language, word})),
            singleConsonant,
        },
    ];
}

export const ROOTS = new Map<string, Root>([
    root(
        "a",
        "to, toward, at, for",
        ["preposition", "aspect particle"],
        "向",
        [["Spanish", "a"]],
    ),
    root(
        "ai",
        "love",
        ["transitive verb"],
        "爱",
        [["Chinese", "爱"]],
    ),
    root(
        "ak",
        "act, behave, appear, seem, express",
        ["intransitive verb"],
        "表",
        [["English", "act"]],
    ),
    root(
        "an",
        "animal, beast",
        ["noun"],
        "兽",
        [["English", "animal"], ["Spanish", "animal"]],
    ),
    root(
        "ao",
        "strange, unknown, mysterious",
        ["adjective"],
        "奥",
        [["Chinese", "奥"]],
    ),
    root(
        "as",
        "make, cause, volitive",
        ["voice particle"],
        "使",
        [["Spanish", "hacer"]],
        "z",
    ),
    root(
        "ba",
        "hold, wield, handle",
        ["transitive verb"],
        "把",
        [["Chinese", "把"]],
        "b",
    ),
    root(
        "bai",
        "hundred",
        ["numeral"],
        "百",
        [["Chinese", "百"]],
    ),
    root(
        "bak",
        "cow, bovine",
        ["noun"],
        "牛",
        [["Spanish", "vaca"]],
    ),
    root(
        "ban",
        "half",
        ["numeral"],
        "半",
        [["Chinese", "半"]],
    ),
    root(
        "bao",
        "bag, package, bundle; to cover, to wrap",
        ["transitive verb"],
        "包",
        [["Chinese", "包"]],
    ),
    root(
        "bas",
        "empty, blank, vacant, hollow",
        ["adjective"],
        "空",
        [["Spanish", "vacío"]],
    ),
    root(
        "be",
        "beautiful, nice",
        ["adjective"],
        "美",
        [["Spanish", "bello"]],
    ),
    root(
        "bek",
        "back, behind, after",
        ["positional"],
        "后",
        [["English", "back"]],
    ),
    root(
        "ben",
        "bend, change, become",
        ["transitive verb", "aspect particle"],
        "变",
        [["Chinese", "变"], ["English", "bend"]],
    ),
    root(
        "bes",
        "time, instance, action, turn, once",
        ["noun"],
        "次",
        [["Spanish", "vez"]],
        "v",
    ),
    root(
        "bi",
        "live, reside, life",
        ["intransitive verb"],
        "活",
        [["Spanish", "vivir"]],
    ),
    root(
        "bik",
        "big, large, old",
        ["adjective"],
        "大",
        [["English", "big"]],
    ),
    root(
        "bin",
        "freeze, cold",
        ["adjective"],
        "冰",
        [["Chinese", "冰"]],
    ),
    root(
        "bis",
        "visit, travel, tour, guest",
        ["intransitive verb"],
        "客",
        [["Spanish", "visitar"], ["English", "visit"]],
    ),
    root(
        "bo",
        "fly",
        ["intransitive verb"],
        "飞",
        [["Spanish", "volar"]],
    ),
    root(
        "boi",
        "yell, shout, howl, bark, moo, meow (etc., any animal sound)",
        ["intransitive verb"],
        "喊",
        [["French", "aboyer"]]
    ),
    root(
        "bok",
        "mouth, hole open at one end",
        ["noun"],
        "孔",
        [["Spanish", "boca"]],
    ),
    root(
        "bon",
        "under, bottom, bum",
        ["positional"],
        "下",
        [["English", "bottom"], ["Chinese", "本"]],
    ),
    root(
        "bos",
        "voice, sound, noise, make noise",
        ["intransitive verb"],
        "声",
        [["Spanish", "voz"]],
    ),
    root(
        "bu",
        "repair, recompense, compensate, fill in",
        ["transitive verb"],
        "补",
        [["Chinese", "补"]],
    ),
    root(
        "buk",
        "book",
        ["noun"],
        "书",
        [["English", "book"]],
    ),
    root(
        "bun",
        "boon, prize, accomplishment, asset",
        ["noun"],
        "财",
        [["English", "boon"]],
    ),
    root(
        "bus",
        "seek, search, look for, want, aim, intentionally",
        ["transitive verb"],
        "找",
        [["Spanish", "buscar"]],
    ),
    root(
        "ca",
        "fall short, different, minus, mistake, error, bad",
        ["intransitive verb"],
        "差",
        [["Chinese", "差"]],
    ),
    root(
        "cai",
        "boil, tea",
        ["intransitive verb"],
        "茶",
        [["Chinese", "茶"], ["Hindi", "चाय"]],
    ),
    root(
        "cak",
        "four",
        ["numeral"],
        "四",
        [["Hindi", "चार"]],
    ),
    root(
        "can",
        "sing, praise",
        ["intransitive verb"],
        "唱",
        [["Chinese", "唱"], ["French", "chanter"]],
    ),
    root(
        "cao",
        "long, string, strip, ribbon, extreme, too",
        ["adjective", "adverb"],
        "条",
        [["Chinese", "条"], ["Chinese", "超"]],
    ),
    root(
        "cas",
        "click, snap, pop",
        ["intransitive verb"],
        "咔",
        [["Spanish", "chasquear"]],
    ),
    root(
        "ce",
        "car, vehicle",
        ["noun"],
        "车",
        [["Chinese", "車"]],
    ),
    root(
        "cek",
        "cut, slice, separate",
        ["transitive verb"],
        "切",
        [["Chinese", "切割"]],
    ),
    root(
        "cen",
        "front, face, before",
        ["positional"],
        "前",
        [["Chinese", "前"]],
    ),
    root(
        "ces",
        "chase, pursue, follow",
        ["transitive verb"],
        "追",
        [["English", "chase"]],
    ),
    root(
        "ci",
        "seven",
        ["numeral"],
        "七",
        [["Chinese", "七"]],
    ),
    root(
        "cik",
        "child, offspring, (diminutive)",
        ["noun"],
        "子",
        [["Spanish", "chico"], ["Russian", "-чик"]],
    ),
    root(
        "cin",
        "politely request, please",
        ["transitive verb"],
        "请",
        [["Chinese", "请"]],
        "c",
    ),
    root(
        "cis",
        "cheese, form, coagulate, curdle",
        ["intransitive verb"],
        "酪",
        [["English", "cheese"]],
    ),
    root(
        "co",
        "eat, drink, consume",
        ["transitive verb"],
        "吃",
        [["Chinese", "吃"]],
    ),
    root(
        "coi",
        "float, drift",
        ["intransitive verb"],
        "漂",
        [["Vietnamese", "trôi"]],
    ),
    root(
        "cok",
        "ball, sphere",
        ["noun"],
        "球",
        [["Chinese", "球体"]],
    ),
    root(
        "con",
        "insect, worm, invertebrate, arthropod",
        ["noun"],
        "虫",
        [["Chinese", "虫"]],
    ),
    root(
        "cos",
        "trust, believe in, faith, confidence",
        ["transitive verb"],
        "信",
        [["English", "trust"]],
    ),
    root(
        "cu",
        "out, send, happen, leave, quit, depart",
        ["intransitive verb"],
        "出",
        [["Chinese", "出"]],
    ),
    root(
        "cuk",
        "store, stockpile, preserve, save, keep",
        ["transitive verb"],
        "储",
        [["Chinese", "储备"], ["Chinese", "储存"]],
    ),
    root(
        "cun",
        "vitality, life, lust, spring, alive",
        ["noun"],
        "春",
        [["Chinese", "春"]],
    ),
    root(
        "cus",
        "choose, select",
        ["transitive verb"],
        "选",
        [["English", "choose"]],
    ),
    root(
        "da",
        "hit, strike",
        ["transitive verb"],
        "打",
        [["Chinese", "打"]],
    ),
    root(
        "dai",
        "support, carry, bring",
        ["transitive verb"],
        "带",
        [["Chinese", "带"]],
    ),
    root(
        "dak",
        "dark, black",
        ["adjective"],
        "黑",
        [["English", "dark"]],
    ),
    root(
        "dan",
        "simple, easy",
        ["adjective"],
        "单",
        [["Chinese", "单"]],
    ),
    root(
        "dao",
        "arrive, until, up to",
        ["preposition"],
        "到",
        [["Chinese", "到"]],
    ),
    root(
        "das",
        "ten",
        ["numeral"],
        "十",
        [["Hindi", "दस"]],
    ),
    root(
        "de",
        "from, off of, away from",
        ["preposition", "linking particle"],
        "从",
        [["Spanish", "de"]],
        "d",
    ),
    root(
        "dek",
        "thin, slender",
        ["adjective"],
        "细",
        [["Spanish", "delgado"]],
    ),
    root(
        "den",
        "inside",
        ["positional"],
        "内",
        [["Spanish", "dentro"]],
    ),
    root(
        "des",
        "speak, say, mean, signify",
        ["transitive verb"],
        "言",
        [["Spanish", "decir"]],
    ),
    root(
        "do",
        "sleep",
        ["intransitive verb"],
        "睡",
        [["Spanish", "dormir"]],
    ),
    root(
        "doi",
        "sorrow, sadness, pain",
        ["noun"],
        "悲",
        [["Spanish", "duelo"]]
    ),
    root(
        "dok",
        "dog",
        ["noun"],
        "犬",
        [["English", "dog"]],
    ),
    root(
        "don",
        "understand",
        ["transitive verb"],
        "懂",
        [["Chinese", "懂"]],
    ),
    root(
        "dos",
        "two, pair",
        ["numeral"],
        "二",
        [["Spanish", "dos"]],
    ),
    root(
        "du",
        "belly, stomach",
        ["noun"],
        "肚",
        [["Chinese", "肚"]],
    ),
    root(
        "dus",
        "city",
        ["noun"],
        "市",
        [["Chinese", "都市"]],
    ),
    root(
        "dun",
        "shield, guard, cover, protect",
        ["transitive verb"],
        "盾",
        [["Chinese", "盾"]],
    ),
    root(
        "duk",
        "hard, strong, tough, stiff",
        ["adjective"],
        "刚",
        [["Spanish", "duro"]],
    ),
    root(
        "e",
        "hungry, greedy, starve",
        ["adjective"],
        "饿",
        [["Chinese", "饿"]],
    ),
    root(
        "ek",
        "far, distant, foreign, outside, apart",
        ["positional"],
        "外",
        [["English", "ex-"], ["Spanish", "ex-"]],
    ),
    root(
        "en",
        "in, on, continuous",
        ["preposition", "aspect particle"],
        "在",
        [["Spanish", "en"]],
        "n",
    ),
    root(
        "es",
        "be, absolutive",
        ["voice particle"],
        "是",
        [["Spanish", "es"], ["Spanish", "estar"]],
        "s",
    ),
    root(
        "ga",
        "gather, assemble, condense, aggregate",
        ["intransitive verb"],
        "集",
        [["English", "gather"]],
    ),
    root(
        "gai",
        "should, ought",
        ["adverb"],
        "该",
        [["Chinese", "该"]],
        "g",
    ),
    root(
        "gak",
        "cat",
        ["noun"],
        "猫",
        [["Spanish", "gato"]],
    ),
    root(
        "gan",
        "stick, pole, rod, bar",
        ["noun"],
        "杆",
        [["Chinese", "杆"], ["Chinese", "杠"], ["Chinese", "竿"]],
    ),
    root(
        "gao",
        "tall, high, noble",
        ["adjective"],
        "高",
        [["Chinese", "高"]],
    ),
    root(
        "gas",
        "gas, air, odor",
        ["noun"],
        "气",
        [["English", "gas"], ["Spanish", "gas"]],
    ),
    root(
        "ge",
        "give, offer",
        ["transitive verb"],
        "给",
        [["Chinese", "给"]],
    ),
    root(
        "gek",
        "get, receive",
        ["transitive verb"],
        "收",
        [["English", "get"]],
    ),
    root(
        "gen",
        "root, source, origin",
        ["noun"],
        "根",
        [["Chinese", "根"]],
    ),
    root(
        "ges",
        "rule, law",
        ["noun"],
        "规",
        [["Chinese", "规则"]],
    ),
    root(
        "gi",
        "guide, steer, direct, lead, govern",
        ["transitive verb"],
        "导",
        [["Spanish", "guiar"]],
    ),
    root(
        "gik",
        "geek, enthusiast, specialist",
        ["noun"],
        "迷",
        [["English", "geek"]],
    ),
    root(
        "gis",
        "hide, conceal, obscure, secret",
        ["transitive verb"],
        "秘",
        [["Turkish", "giz"], ["Turkish", "gizlemek"]],
    ),
    root(
        "gin",
        "green",
        ["adjective"],
        "绿",
        [["English", "green"]],
    ),
    root(
        "go",
        "enough, adequate, suffice",
        ["adjective"],
        "够",
        [["Chinese", "够"]],
    ),
    root(
        "goi",
        "expensive, valuable, precious",
        ["adjective"],
        "贵",
        [["Chinese", "贵"]],
    ),
    root(
        "gok",
        "drop, bead, spot, point, grain",
        ["noun"],
        "点",
        [["Spanish", "gota"]],
    ),
    root(
        "gon",
        "public, shared, government",
        ["adjective"],
        "公",
        [["Chinese", "公"], ["Chinese", "共"]],
    ),
    root(
        "gos",
        "fruit, egg, produce, results",
        ["noun"],
        "果",
        [["Chinese", "果实"]],
    ),
    root(
        "gu",
        "old, tradition, ancient",
        ["adjective"],
        "故",
        [["Chinese", "故"]],
    ),
    root(
        "guk",
        "group, together",
        ["noun"],
        "组",
        [["English", "group"], ["Spanish", "grupo"], ["Chinese", "共同"]],
    ),
    root(
        "gun",
        "closed, shut",
        ["adjective"],
        "关",
        [["Chinese", "关"]],
    ),
    root(
        "gus",
        "story, narrative, matter",
        ["noun"],
        "事",
        [["Chinese", "故事"]],
    ),
    root(
        "ha",
        "laugh",
        ["intransitive verb", "interjection"],
        "哈",
        [["Chinese", "哈哈"], ["English", "haha"], ["Spanish", "jaja"]],
    ),
    root(
        "hai",
        "still, yet, additional, surplus",
        ["adverb"],
        "还",
        [["Chinese", "还"]],
    ),
    root(
        "hak",
        "heart, emotion, feeling, center",
        ["noun"],
        "心",
        [["English", "heart"]],
    ),
    root(
        "han",
        "reverse, oppose, opposite, against, respond, react",
        ["transitive verb"],
        "反",
        [["Chinese", "返"], ["Chinese", "反"]],
    ),
    root(
        "hao",
        "good, beneficial, pleasant, beautiful, just",
        ["adjective", "adverb"],
        "好",
        [["Chinese", "好"]],
    ),
    root(
        "has",
        "anger, wrath",
        ["noun"],
        "怒",
        [["French", "rage"], ["Hindi", "ख़श्म"]],
    ),
    root(
        "he",
        "heal, health, healthy",
        ["intransitive verb"],
        "健",
        [["English", "health"]],
    ),
    root(
        "hek",
        "hate, be disgusted by",
        ["transitive verb"],
        "恨",
        [["English", "hate"], ["Dutch", "hekel"]],
    ),
    root(
        "hen",
        "very, intensely",
        ["adverb"],
        "很",
        [["Chinese", "很"]],
        "h",
    ),
    root(
        "hes",
        "breathe, smell",
        ["intransitive verb"],
        "吸",
        [["Spanish", "respirar"], ["Chinese", "呼吸"]],
    ),
    root(
        "ho",
        "thick, ample, deep, wide, dense, fat",
        ["adjective"],
        "厚",
        [["Chinese", "厚"]],
    ),
    root(
        "hoi",
        "turn, revolve, rotate, turn back, return, orbit",
        ["intransitive verb"],
        "回",
        [["Chinese", "回"]],
    ),
    root(
        "hok",
        "hot, heat",
        ["adjective"],
        "热",
        [["English", "hot"]],
    ),
    root(
        "hon",
        "red",
        ["adjective"],
        "红",
        [["Chinese", "红"]],
    ),
    root(
        "hos",
        "horse, equine",
        ["noun"],
        "马",
        [["English", "horse"]],
    ),
    root(
        "hu",
        "game, play, have fun",
        ["intransitive verb"],
        "玩",
        [["Spanish", "jugar"]],
    ),
    root(
        "huk",
        "hook, bend, curve, corner",
        ["noun"],
        "角",
        [["English", "hook"], ["Dutch", "hoek"]],
    ),
    root(
        "hun",
        "mix, mingle, together, marriage",
        ["intransitive verb"],
        "混",
        [["Chinese", "混"], ["Spanish", "junto"], ["Chinese", "婚"]],
    ),
    root(
        "hus",
        "monkey, ape, naughty, tricksy",
        ["noun"],
        "猴",
        [["Chinese", "猴子"]],
    ),
    root(
        "i",
        "and, add, again",
        ["coordinating conjunction"],
        "又",
        [["Spanish", "y"]],
    ),
    root(
        "ik",
        "burn, fire",
        ["intransitive verb"],
        "火",
        [["Latin", "ignis"], ["English", "ignite"]],
    ),
    root(
        "in",
        "pull, stretch, extend, exaggerate",
        ["transitive verb"],
        "引",
        [["Chinese", "引"]],
    ),
    root(
        "is",
        "left",
        ["positional"],
        "左",
        [["Spanish", "izquierdo"]],
    ),
    root(
        "ja",
        "family, household",
        ["noun"],
        "家",
        [["Chinese", "家"]],
    ),
    root(
        "jai",
        "victory, glory, long live",
        ["noun"],
        "胜",
        [["Hindi", "जय"]],
    ),
    root(
        "jak",
        "coat, jacket",
        ["noun"],
        "袄",
        [["English", "jacket"]],
    ),
    root(
        "jan",
        "flat, sheet, surface, platform",
        ["adjective"],
        "张",
        [["Chinese", "张"]],
    ),
    root(
        "jao",
        "foot, leg",
        ["noun"],
        "脚",
        [["Chinese", "脚"]],
    ),
    root(
        "jas",
        "true, real, genuine, correct, serious",
        ["adjective"],
        "真",
        [["Chinese", "真实"]],
    ),
    root(
        "je",
        "this, that",
        ["determiner"],
        "这",
        [["Chinese", "这"]],
        "j",
    ),
    root(
        "jek",
        "think, believe, feel",
        ["transitive verb"],
        "觉",
        [["Chinese", "觉得"]],
    ),
    root(
        "jen",
        "person, human",
        ["noun"],
        "人",
        [["Chinese", "人"]],
    ),
    root(
        "jes",
        "introduce, bring up, advise, comment, suggest",
        ["transitive verb"],
        "介",
        [["Chinese", "介紹"], ["English", "suggest"]],
    ),
    root(
        "ji",
        "number, amount, some, ordinal, unit, count, calculate",
        ["transitive verb"],
        "计",
        [["Chinese", "几"], ["Chinese", "计"], ["Chinese", "第"]],
    ),
    root(
        "jik",
        "structure, organization, institution",
        ["noun"],
        "机",
        [["Chinese", "机关"], ["Chinese", "机构"]],
    ),
    root(
        "jin",
        "metal, money",
        ["noun"],
        "金",
        [["Chinese", "金"]],
    ),
    root(
        "jis",
        "skill, craft, technology, technique, art",
        ["noun"],
        "术",
        [["Chinese", "技术"]],
    ),
    root(
        "jo",
        "just, only, already, as soon as",
        ["adverb"],
        "就",
        [["Chinese", "就"]],
    ),
    root(
        "joi",
        "watch out, pay attention, beware, nurture, guard",
        ["transitive verb"],
        "注",
        [["Chinese", "注意"]]
    ),
    root(
        "jok",
        "humor, joke",
        ["noun"],
        "逗",
        [["English", "joke"]],
    ),
    root(
        "jon",
        "seed, bean, gamete, gene, sexual, species",
        ["noun"],
        "种",
        [["Chinese", "种"]],
    ),
    root(
        "jos",
        "table, desk",
        ["noun"],
        "桌",
        [["Chinese", "桌子"]],
    ),
    root(
        "ju",
        "raise, lift, cite, demonstrate",
        ["transitive verb"],
        "举",
        [["Chinese", "举"]],
    ),
    root(
        "juk",
        "if",
        ["subordinating conjunction"],
        "如",
        [["Chinese", "如果"]],
    ),
    root(
        "jun",
        "bacteria, mold",
        ["noun"],
        "菌",
        [["Chinese", "菌"]],
    ),
    root(
        "jus",
        "juice, liquid, blood",
        ["noun"],
        "汁",
        [["English", "juice"]],
    ),
    root(
        "ka",
        "fall, drop, down",
        ["intransitive verb"],
        "跌",
        [["Spanish", "caer"]],
    ),
    root(
        "kai",
        "start, open, begin, operate",
        ["transitive verb", "aspect particle"],
        "开",
        [["Chinese", "开"]],
    ),
    root(
        "kak",
        "feces",
        ["noun"],
        "屎",
        [["Spanish", "caca"]],
    ),
    root(
        "kan",
        "see, read",
        ["transitive verb"],
        "看",
        [["Chinese", "看"]],
    ),
    root(
        "kao",
        "test, inspect, consider, try",
        ["transitive verb"],
        "考",
        [["Chinese", "考"]],
    ),
    root(
        "kas",
        "house, home, building",
        ["noun"],
        "房",
        [["Spanish", "casa"]],
    ),
    root(
        "ke",
        "what, which",
        ["determiner"],
        "何",
        [["Spanish", "qué"]],
        "k",
    ),
    root(
        "kek",
        "sibling",
        ["noun"],
        "兄",
        [["Malay", "kakak"], ["Arabic", "شقيق"]],
    ),
    root(
        "ken",
        "can, may, possible, able",
        ["adverb"],
        "能",
        [["English", "can"], ["Chinese", "可能"]],
    ),
    root(
        "kes",
        "grow, increase",
        ["intransitive verb"],
        "增",
        [["Spanish", "crecer"]],
    ),
    root(
        "ki",
        "(relativizer)",
        ["relativizer"],
        "者",
        [["French", "qui"]],
        "q",
    ),
    root(
        "kik",
        "remove, take away, clean off",
        ["transitive verb"],
        "除",
        [["Spanish", "quitar"]],
    ),
    root(
        "kin",
        "keen, sharp, witty, clever, blade",
        ["adjective"],
        "锐",
        [["English", "keen"]],
    ),
    root(
        "kis",
        "kiss",
        ["transitive verb"],
        "吻",
        [["English", "kiss"]],
    ),
    root(
        "ko",
        "door, opening, hole open at both ends",
        ["noun"],
        "口",
        [["Chinese", "口"]],
    ),
    root(
        "koi",
        "body, torso, corpse",
        ["noun"],
        "身",
        [["Spanish", "cuerpo"]]
    ),
    root(
        "kok",
        "short (in length, distance, duration)",
        ["adjective"],
        "短",
        [["Spanish", "corto"]],
    ),
    root(
        "kon",
        "recognize, be familiar with",
        ["transitive verb"],
        "识",
        [["Spanish", "conocer"]],
    ),
    root(
        "kos",
        "thing, object, tool",
        ["noun"],
        "物",
        [["Spanish", "cosa"]],
    ),
    root(
        "ku",
        "bitter, suffering, unpleasant, alkali",
        ["adjective"],
        "苦",
        [["Chinese", "苦"]],
    ),
    root(
        "kuk",
        "cook, burn, heat up",
        ["transitive verb"],
        "烧",
        [["English", "cook"]],
    ),
    root(
        "kun",
        "yellow, orange, brown",
        ["adjective"],
        "黄",
        [["Malay", "kuning"]],
    ),
    root(
        "kus",
        "hear",
        ["transitive verb"],
        "听",
        [["Spanish", "escuchar"]],
    ),
    root(
        "la",
        "side, edge, direction",
        ["positional"],
        "边",
        [["Spanish", "lado"]],
    ),
    root(
        "lai",
        "come, become, exhortative",
        ["intransitive verb"],
        "来",
        [["Chinese", "来"]],
        "l",
    ),
    root(
        "lak",
        "milk",
        ["noun"],
        "奶",
        [["Latin", "lac"]],
    ),
    root(
        "lan",
        "blue",
        ["adjective"],
        "蓝",
        [["Chinese", "蓝"]],
    ),
    root(
        "lao",
        "allow, let, open",
        ["transitive verb"],
        "许",
        [["English", "allow"]],
    ),
    root(
        "las",
        "glass, transparent",
        ["noun"],
        "玻",
        [["English", "glass"]],
    ),
    root(
        "le",
        "type, kind, class",
        ["noun"],
        "类",
        [["Chinese", "类"]],
    ),
    root(
        "lek",
        "electric, electricity",
        ["noun"],
        "电",
        [["English", "electric"], ["Spanish", "eléctrico"]],
    ),
    root(
        "len",
        "slow",
        ["adjective"],
        "慢",
        [["Spanish", "lento"]],
    ),
    root(
        "les",
        "read, understand, interpret, study",
        ["transitive verb"],
        "读",
        [["German", "lesen"]],
    ),
    root(
        "li",
        "ritual, ceremony, etiquette, custom, gift",
        ["noun"],
        "礼",
        [["Chinese", "礼"]],
    ),
    root(
        "lik",
        "lightweight, fragile, weak, slight, minor",
        ["adjective"],
        "轻",
        [["Spanish", "ligero"]],
    ),
    root(
        "lin",
        "clean, clear",
        ["adjective"],
        "洁",
        [["Spanish", "limpio"]],
    ),
    root(
        "lis",
        "ready, clever, ripe, alert",
        ["adjective"],
        "备",
        [["Spanish", "listo"]],
    ),
    root(
        "lo",
        "low, short",
        ["adjective"],
        "矮",
        [["English", "low"]],
    ),
    root(
        "loi",
        "then, next, later, so, therefore",
        ["adverb"],
        "而",
        [["Spanish", "luego"]],
    ),
    root(
        "lok",
        "crazy",
        ["adjective"],
        "狂",
        [["Spanish", "loco"]],
    ),
    root(
        "lon",
        "unique, alone, solitary",
        ["adjective"],
        "独",
        [["English", "lone"]],
    ),
    root(
        "los",
        "level, floor, layer, stratum",
        ["noun"],
        "层",
        [["Chinese", "楼层"]],
    ),
    root(
        "lu",
        "flow, pour, spill, move, circulate",
        ["intransitive verb"],
        "流",
        [["Chinese", "流"], ["Spanish", "fluir"]],
    ),
    root(
        "luk",
        "place, location",
        ["noun"],
        "所",
        [["Spanish", "lugar"]],
    ),
    root(
        "lun",
        "round, circle, wheel, cycle",
        ["noun"],
        "轮",
        [["Chinese", "轮"]],
    ),
    root(
        "lus",
        "light, intelligence, clarity, perspective",
        ["noun"],
        "光",
        [["Spanish", "luz"]],
    ),
    root(
        "ma",
        "parent, older relative",
        ["noun"],
        "亲",
        [["English", "ma"], ["Spanish", "mamá"], ["Chinese", "妈妈"], ["Hindi", "मामा"]],
    ),
    root(
        "mai",
        "buy, sell, trade, exchange, swap, switch",
        ["transitive verb"],
        "买",
        [["Chinese", "卖"], ["Chinese", "买"]],
    ),
    root(
        "mak",
        "make, construct, create, prepare",
        ["transitive verb"],
        "作",
        [["English", "make"], ["Dutch", "maken"], ["German", "machen"]],
    ),
    root(
        "man",
        "full, satisfied, complete, whole, entire",
        ["adjective"],
        "满",
        [["Chinese", "满"]],
    ),
    root(
        "mao",
        "hair, fur, feather, wool, bristle",
        ["noun"],
        "毛",
        [["Chinese", "毛"]],
    ),
    root(
        "mas",
        "more, most",
        ["adverb"],
        "更",
        [["Spanish", "más"]],
    ),
    root(
        "me",
        "all, each, every",
        ["determiner"],
        "每",
        [["Chinese", "每"]],
    ),
    root(
        "mek",
        "mechanism, device, tool, machine, contraption",
        ["noun"],
        "器",
        [["English", "mechanism"], ["Spanish", "mecanismo"]],
    ),
    root(
        "men",
        "plural, many, much, a lot",
        ["number particle"],
        "们",
        [["English", "many"], ["Chinese", "们"]],
    ),
    root(
        "mes",
        "middle, center, between, among",
        ["positional"],
        "中",
        [["English", "meso-"], ["Spanish", "medio"]],
    ),
    root(
        "mi",
        "1st person",
        ["pronoun"],
        "我",
        [["English", "me"], ["Spanish", "mí"]],
        "m",
    ),
    root(
        "mik",
        "friend, kind, amicable",
        ["noun"],
        "友",
        [["Spanish", "amigo"]],
    ),
    root(
        "min",
        "name, word, call, refer",
        ["transitive verb"],
        "名",
        [["Chinese", "名"]],
    ),
    root(
        "mis",
        "miss, err, mistake",
        ["intransitive verb"],
        "失",
        [["English", "miss"], ["English", "mistake"]],
    ),
    root(
        "mo",
        "die, end, ending",
        ["intransitive verb"],
        "末",
        [["Spanish", "morir"], ["Chinese", "末"]],
    ),
    root(
        "moi",
        "soft, smooth, mild, easy, slight, relaxed",
        ["adjective"],
        "软",
        [["Spanish", "muelle"]],
    ),
    root(
        "mok",
        "mock, copy, imitate, resemble",
        ["transitive verb"],
        "仿",
        [["English", "mock"]],
    ),
    root(
        "mon",
        "mountain, hill, mound, pile, heap, mass",
        ["noun"],
        "山",
        [["English", "mound"], ["English", "mountain"], ["Spanish", "montón"], ["Spanish", "montaña"]],
    ),
    root(
        "mos",
        "must, have to (epistemic and deontic senses)",
        ["adverb"],
        "必",
        [["English", "must"]],
    ),
    root(
        "mu",
        "tree, post, column, wood",
        ["noun"],
        "木",
        [["Chinese", "木"]],
    ),
    root(
        "muk",
        "free, open, unencumbered, loose, relaxed, non-binary, gender-nonconforming",
        ["adjective"],
        "放",
        [["Hindi", "मुक्त"]],
    ),
    root(
        "mun",
        "moon, month",
        ["noun"],
        "月",
        [["English", "moon"]],
    ),
    root(
        "mus",
        "mouse, rodent",
        ["noun"],
        "鼠",
        [["English", "mouse"], ["Latin", "mūs"]],
    ),
    root(
        "na",
        "swim",
        ["intransitive verb"],
        "泳",
        [["Spanish", "nadar"]],
    ),
    root(
        "nai",
        "nine",
        ["numeral"],
        "九",
        [["English", "nine"]],
    ),
    root(
        "nak",
        "nature, character, base, bare, naked",
        ["adjective"],
        "露",
        [["Spanish", "natural"], ["English", "natural"], ["English", "naked"]],
    ),
    root(
        "nan",
        "male, masculine",
        ["adjective"],
        "男",
        [["Chinese", "男"]],
    ),
    root(
        "nao",
        "brain, mind",
        ["noun"],
        "脑",
        [["Chinese", "脑"]],
    ),
    root(
        "nas",
        "nation, people, ethnicity",
        ["noun"],
        "国",
        [["English", "nation"], ["Spanish", "nación"]],
    ),
    root(
        "ne",
        "system, network, economy, environment, internet",
        ["noun"],
        "网",
        [["English", "net"]],
    ),
    root(
        "nek",
        "neck, stem",
        ["noun"],
        "颈",
        [["English", "neck"]],
    ),
    root(
        "nen",
        "year",
        ["noun"],
        "年",
        [["Chinese", "年"]],
    ),
    root(
        "nes",
        "essence, concept, abstract noun",
        ["nominalizer"],
        "性",
        [["English", "-ness"]],
    ),
    root(
        "ni",
        "2nd person",
        ["pronoun"],
        "你",
        [["Chinese", "你"]],
    ),
    root(
        "nik",
        "meat, flesh, organ",
        ["noun"],
        "肉",
        [["Japanese", "肉"]],
    ),
    root(
        "nin",
        "none, nothing, zero",
        ["numeral"],
        "无",
        [["Spanish", "ninguno"]],
    ),
    root(
        "nis",
        "about, concerning, with regard to",
        ["preposition", "linking particle"],
        "于",
        [["Japanese", "について"]],
    ),
    root(
        "no",
        "no, not",
        ["adverb"],
        "不",
        [["English", "no"], ["Spanish", "no"]],
    ),
    root(
        "noi",
        "nag, annoy, bother, harass, disturb",
        ["transitive verb"],
        "烦",
        [["English", "annoy"]],
    ),
    root(
        "nok",
        "night",
        ["noun"],
        "夕",
        [["Spanish", "noche"], ["Latin", "nox"]],
    ),
    root(
        "non",
        "farm, grow, raise, agriculture",
        ["transitive verb"],
        "农",
        [["Chinese", "农"]],
    ),
    root(
        "nos",
        "nose",
        ["noun"],
        "鼻",
        [["English", "nose"]],
    ),
    root(
        "nu",
        "new, young",
        ["adjective"],
        "新",
        [["English", "new"]],
    ),
    root(
        "nun",
        "noon, daytime",
        ["noun"],
        "午",
        [["English", "noon"]],
    ),
    root(
        "nus",
        "feminine, female",
        ["adjective"],
        "女",
        [["Chinese", "女性"], ["Chinese", "女生"], ["Chinese", "女子"]],
    ),
    root(
        "nuk",
        "nut, bead, pearl",
        ["noun"],
        "珠",
        [["Latin", "nux"], ["English", "nut"]],
    ),
    root(
        "o",
        "or, other",
        ["adjective", "coordinating conjunction"],
        "另",
        [["English", "or"], ["Spanish", "otro"]],
    ),
    root(
        "oi",
        "oh, hey",
        ["interjection"],
        "喂",
        [["Chinese", "喂"], ["English", "oi"], ["Japanese", "おい"]],
    ),
    root(
        "ok",
        "eight",
        ["numeral"],
        "八",
        [["Spanish", "ocho"]],
    ),
    root(
        "on",
        "fungus, mushroom",
        ["noun"],
        "菇",
        [["Spanish", "hongo"]],
    ),
    root(
        "os",
        "bear",
        ["noun"],
        "熊",
        [["Spanish", "oso"]],
    ),
    root(
        "pa",
        "stand up, stop, halt, be still",
        ["intransitive verb", "aspect particle"],
        "站",
        [["Spanish", "parar"]],
    ),
    root(
        "pai",
        "arrange, put in order, oversee, row",
        ["transitive verb"],
        "排",
        [["Chinese", "排"]],
    ),
    root(
        "pak",
        "bird",
        ["noun"],
        "鸟",
        [["Spanish", "pájaro"], ["Hindi", "पक्षी"]],
    ),
    root(
        "pan",
        "bread, rice, starch, grain",
        ["noun"],
        "饭",
        [["Spanish", "pan"], ["Chinese", "饭"]],
    ),
    root(
        "pao",
        "power, energy, strength",
        ["noun"],
        "力",
        [["English", "power"]],
    ),
    root(
        "pas",
        "pass, cross, across, on the other side of, experiential, spend time",
        ["preposition", "aspect particle"],
        "过",
        [["English", "pass"], ["Spanish", "pasar"]],
        "p",
    ),
    root(
        "pe",
        "lose, pay, suffer",
        ["transitive verb"],
        "损",
        [["English", "pay"], ["Spanish", "perder"], ["Spanish", "pena"]],
    ),
    root(
        "pek",
        "sticky, adhere, glue, attach",
        ["intransitive verb"],
        "黏",
        [["Spanish", "pegar"]],
    ),
    root(
        "pen",
        "slice, sheet, paper, card, leaf",
        ["noun"],
        "片",
        [["Chinese", "片"]],
    ),
    root(
        "pes",
        "weight, mass, importance, heavy",
        ["noun"],
        "重",
        [["Spanish", "peso"]],
    ),
    root(
        "pi",
        "skin, outside, edge, peel, surface",
        ["positional"],
        "皮",
        [["English", "peel"], ["Spanish", "piel"], ["Chinese", "皮"]],
    ),
    root(
        "pik",
        "picture, image, depiction, explanation",
        ["noun"],
        "像",
        [["English", "picture"]],
    ),
    root(
        "pin",
        "prick, pierce, stab, pin, thorn",
        ["transitive verb"],
        "刺",
        [["English", "pin"], ["Spanish", "pinchar"]],
    ),
    root(
        "pis",
        "piece, part, drop, singulative",
        ["noun"],
        "块",
        [["English", "piece"], ["Spanish", "pieza"]],
    ),
    root(
        "po",
        "poor, helpless, forlorn, meager, sparse, few, scarce",
        ["adjective"],
        "乏",
        [["English", "poor"], ["Spanish", "pobre"], ["Spanish", "poco"]],
    ),
    root(
        "poi",
        "chicken, fowl",
        ["noun"],
        "鸡",
        [["Spanish", "pollo"]],
    ),
    root(
        "pok",
        "pig",
        ["noun"],
        "猪",
        [["Spanish", "puerco"]],
    ),
    root(
        "pon",
        "put, place, add, set",
        ["transitive verb"],
        "加",
        [["Spanish", "poner"]],
    ),
    root(
        "pos",
        "position, role, place, status",
        ["noun"],
        "位",
        [["English", "position"], ["Spanish", "puesto"], ["Spanish", "posición"]],
    ),
    root(
        "pu",
        "way, road, path, direction",
        ["noun"],
        "路",
        [["Russian", "путь"]],
    ),
    root(
        "puk",
        "conflict, fight, war",
        ["intransitive verb"],
        "争",
        [["Spanish", "pugnar"]],
    ),
    root(
        "pun",
        "fundamental, basic, basis",
        ["noun"],
        "基",
        [["Spanish", "fundamental"], ["English", "fundamental"]],
    ),
    root(
        "pus",
        "complex, difficult",
        ["adjective"],
        "复",
        [["Chinese", "复杂"]],
    ),
    root(
        "sa",
        "know",
        ["transitive verb"],
        "知",
        [["Spanish", "saber"]],
    ),
    root(
        "sai",
        "vegetable, plant",
        ["noun"],
        "菜",
        [["Chinese", "菜"]],
    ),
    root(
        "sak",
        "alcohol",
        ["noun"],
        "酒",
        [["Japanese", "酒"]],
    ),
    root(
        "san",
        "three",
        ["numeral"],
        "三",
        [["Chinese", "三"]],
    ),
    root(
        "sao",
        "early, morning",
        ["adjective"],
        "早",
        [["Chinese", "早"]],
    ),
    root(
        "sas",
        "sauce, dressing",
        ["noun"],
        "酱",
        [["English", "sauce"], ["Spanish", "salsa"]],
    ),
    root(
        "se",
        "self, reflexive",
        ["pronoun"],
        "己",
        [["Spanish", "se"]],
    ),
    root(
        "sek",
        "dry, thirsty",
        ["adjective"],
        "干",
        [["Spanish", "seco"]],
    ),
    root(
        "sen",
        "sit, stay, remain, continue",
        ["intransitive verb", "aspect particle"],
        "坐",
        [["Spanish", "sentar"]],
    ),
    root(
        "ses",
        "six",
        ["numeral"],
        "六",
        [["Spanish", "seis"]],
    ),
    root(
        "so",
        "color",
        ["noun"],
        "色",
        [["Chinese", "色"]],
    ),
    root(
        "soi",
        "break, shatter, shred",
        ["transitive verb"],
        "碎",
        [["Chinese", "碎"]],
    ),
    root(
        "sok",
        "lock, latch, secure",
        ["transitive verb"],
        "锁",
        [["Chinese", "锁定"], ["English", "secure"]],
    ),
    root(
        "son",
        "sun, day",
        ["noun"],
        "日",
        [["English", "sun"]],
    ),
    root(
        "sos",
        "social, society",
        ["noun"],
        "交",
        [["English", "social"], ["English", "society"], ["Spanish", "social"], ["Spanish", "sociedad"]],
    ),
    root(
        "su",
        "fast, quick",
        ["adjective"],
        "速",
        [["Chinese", "速"]],
    ),
    root(
        "suk",
        "sugar",
        ["noun"],
        "糖",
        [["Spanish", "azúcar"]],
    ),
    root(
        "sun",
        "sour, acid",
        ["noun"],
        "酸",
        [["Chinese", "酸"]],
    ),
    root(
        "sus",
        "dirty, gross, grubby, unwashed",
        ["adjective"],
        "污",
        [["Spanish", "sucio"]],
    ),
    root(
        "ta",
        "3rd person, thing",
        ["pronoun"],
        "他",
        [["Chinese", "他"], ["Chinese", "她"], ["Chinese", "它"]],
        "t",
    ),
    root(
        "tai",
        "knot, tie, join, connect, relate",
        ["transitive verb"],
        "系",
        [["English", "tie"]],
    ),
    root(
        "tak",
        "fear, afraid",
        ["transitive verb"],
        "怕",
        [["Malay", "takut"]],
    ),
    root(
        "tan",
        "lie, recline",
        ["intransitive verb"],
        "躺",
        [["Chinese", "躺"]],
    ),
    root(
        "tao",
        "thousand",
        ["numeral"],
        "千",
        [["English", "thousand"]],
    ),
    root(
        "tas",
        "cup, bowl",
        ["noun"],
        "杯",
        [["Spanish", "taza"]],
    ),
    root(
        "te",
        "fabric, cloth, clothing",
        ["noun"],
        "布",
        [["Spanish", "tela"]],
    ),
    root(
        "tek",
        "take, buy",
        ["transitive verb"],
        "拿",
        [["English", "take"]],
    ),
    root(
        "ten",
        "sky, weather, heaven, god, holy, sacred",
        ["noun"],
        "天",
        [["Chinese", "天"]],
    ),
    root(
        "tes",
        "taste, smell, flavor, preference",
        ["noun"],
        "味",
        [["English", "taste"]],
    ),
    root(
        "to",
        "head, individual, chief",
        ["noun"],
        "头",
        [["Chinese", "头"]],
    ),
    root(
        "toi",
        "push, extend, postpone, publish, promote, spread, distribute",
        ["transitive verb"],
        "推",
        [["Chinese", "推"]],
    ),
    root(
        "tok",
        "touch, feel, play (instrument)",
        ["transitive verb"],
        "摸",
        [["Spanish", "tocar"]],
    ),
    root(
        "ton",
        "same, common, like, as",
        ["adjective"],
        "同",
        [["Chinese", "同"]],
    ),
    root(
        "tos",
        "throw, throw out, reject, expel, emit, spew, cough",
        ["transitive verb"],
        "扔",
        [["English", "toss"], ["Spanish", "tos"]],
    ),
    root(
        "tu",
        "ground, land, dirt, territory, earth",
        ["noun"],
        "土",
        [["Chinese", "土"]],
    ),
    root(
        "tuk",
        "tube, pipe",
        ["noun"],
        "管",
        [["Spanish", "tubo"], ["English", "tube"]],
    ),
    root(
        "tun",
        "music, harmony",
        ["noun"],
        "乐",
        [["English", "tune"]],
    ),
    root(
        "tus",
        "paint, smear, wipe, coating, layer",
        ["transitive verb"],
        "涂",
        [["Chinese", "涂层"], ["Chinese", "涂饰"]],
    ),
    root(
        "u",
        "five",
        ["numeral"],
        "五",
        [["Chinese", "五"]],
    ),
    root(
        "uk",
        "dance",
        ["intransitive verb"],
        "舞",
        [["Chinese", "舞蹈"]],
    ),
    root(
        "un",
        "one, a, some, any",
        ["numeral"],
        "一",
        [["Spanish", "un"], ["Spanish", "uno"]],
    ),
    root(
        "us",
        "substance, material, matter",
        ["noun"],
        "质",
        [["Chinese", "物质"]],
    ),
    root(
        "wa",
        "water",
        ["noun"],
        "水",
        [["English", "water"], ["Spanish", "agua"]],
    ),
    root(
        "wai",
        "white, pale",
        ["adjective"],
        "白",
        [["English", "white"]],
    ),
    root(
        "wak",
        "walk, move",
        ["intransitive verb"],
        "走",
        [["English", "walk"]],
    ),
    root(
        "wan",
        "late, night, evening",
        ["noun"],
        "晚",
        [["Chinese", "晚"]],
    ),
    root(
        "wao",
        "wow, (exclamation)",
        ["interjection"],
        "哇",
        [["English", "wow"]],
    ),
    root(
        "was",
        "wash",
        ["transitive verb"],
        "洗",
        [["English", "wash"]],
    ),
    root(
        "we",
        "way, state, manner, function, reason",
        ["noun"],
        "为",
        [["English", "way"], ["Chinese", "为"]],
        "w",
    ),
    root(
        "wek",
        "alert, awake, wait, anticipate",
        ["intransitive verb"],
        "醒",
        [["English", "wake"], ["English", "wait"]],
    ),
    root(
        "wen",
        "warm, tender, gentle",
        ["adjective"],
        "温",
        [["Chinese", "温"]],
    ),
    root(
        "wes",
        "bone",
        ["noun"],
        "骨",
        [["Spanish", "hueso"]],
    ),
    root(
        "wi",
        "escape, avoid, flee",
        ["intransitive verb"],
        "逃",
        [["Spanish", "huir"]],
    ),
    root(
        "wik",
        "weak, tired",
        ["adjective"],
        "弱",
        [["English", "weak"]],
    ),
    root(
        "win",
        "win, gain, obtain, succeed",
        ["transitive verb"],
        "赢",
        [["English", "win"]],
    ),
    root(
        "wis",
        "follow, with, in accompaniment",
        ["transitive verb"],
        "跟",
        [["English", "with"]],
    ),
    root(
        "wo",
        "wall, barrier",
        ["noun"],
        "墙",
        [["English", "wall"]],
    ),
    root(
        "wok",
        "work, labor, position, role",
        ["intransitive verb"],
        "工",
        [["English", "work"]],
    ),
    root(
        "won",
        "ask, request, question, problem, issue",
        ["transitive verb"],
        "问",
        [["Chinese", "问"]],
    ),
    root(
        "wos",
        "worsen, decay, decline, rot, deteriorate",
        ["intransitive verb"],
        "朽",
        [["English", "worsen"], ["Malay", "rosot"], ["Malay", "rosak"]],
    ),
    root(
        "xa",
        "sand, powder",
        ["noun"],
        "沙",
        [["Chinese", "沙"]],
    ),
    root(
        "xas",
        "time, hour",
        ["noun"],
        "时",
        [["Chinese", "时间"], ["Chinese", "小时"]],
        "x",
    ),
    root(
        "xai",
        "shy, timid, meek, ashamed",
        ["adjective"],
        "羞",
        [["English", "shy"]],
    ),
    root(
        "xak",
        "branch, department, section, arm, tributary",
        ["noun"],
        "支",
        [["Hindi", "शाखा"]],
    ),
    root(
        "xan",
        "top, over, above, up",
        ["positional"],
        "上",
        [["Chinese", "上"]],
    ),
    root(
        "xao",
        "small, young",
        ["adjective"],
        "小",
        [["Chinese", "小"]],
    ),
    root(
        "xe",
        "write",
        ["transitive verb"],
        "写",
        [["Chinese", "写"]],
    ),
    root(
        "xek",
        "shake, vibrate, sway, move (back and forth)",
        ["intransitive verb"],
        "摇",
        [["English", "shake"]],
    ),
    root(
        "xen",
        "deep, rich, saturated",
        ["adjective"],
        "深",
        [["Chinese", "深"]],
    ),
    root(
        "xes",
        "learn, study",
        ["transitive verb"],
        "学",
        [["Chinese", "学习"]],
    ),
    root(
        "xi",
        "happy, pleased, enjoy, interest",
        ["transitive verb"],
        "喜",
        [["Chinese", "喜"]],
    ),
    root(
        "xik",
        "chic, hip, cool",
        ["adjective"],
        "雅",
        [["French", "chic"]],
    ),
    root(
        "xin",
        "star, week",
        ["noun"],
        "星",
        [["Chinese", "星"]],
    ),
    root(
        "xis",
        "lizard, snake, reptile",
        ["noun"],
        "蜥",
        [["Chinese", "蜥形纲"]],
    ),
    root(
        "xo",
        "hand, arm",
        ["noun"],
        "手",
        [["Chinese", "手"]],
    ),
    root(
        "xoi",
        "taxation, rent, revenue, cost",
        ["noun"],
        "税",
        [["Chinese", "税"]],
    ),
    root(
        "xok",
        "stone, rock",
        ["noun"],
        "石",
        [["Chinese", "石头"], ["English", "rock"]],
    ),
    root(
        "xon",
        "chest, breast",
        ["noun"],
        "胸",
        [["Chinese", "胸"]],
    ),
    root(
        "xos",
        "rest, pause",
        ["intransitive verb"],
        "休",
        [["Chinese", "休息"]],
    ),
    root(
        "xu",
        "shoe",
        ["noun"],
        "鞋",
        [["English", "shoe"]],
    ),
    root(
        "xuk",
        "thank",
        ["transitive verb"],
        "谢",
        [["Arabic", "شكرا"]],
    ),
    root(
        "xun",
        "obey, follow, fit, suit",
        ["transitive verb"],
        "顺",
        [["Chinese", "顺"]],
    ),
    root(
        "xus",
        "comfortable, cozy, snug, relax",
        ["adjective"],
        "舒",
        [["Chinese", "舒适"]],
    ),
    root(
        "ya",
        "press, push, control, print",
        ["transitive verb"],
        "压",
        [["Chinese", "压"]],
    ),
    root(
        "yai",
        "surprised, amazed, be surprised by",
        ["transitive verb"],
        "讶",
        [["Chinese", "讶异"]],
    ),
    root(
        "yak",
        "around, near, about, approximately, almost",
        ["positional", "adverb"],
        "约",
        [["Turkish", "yakın"], ["Japanese", "約"]],
    ),
    root(
        "yan",
        "sheep, goat",
        ["noun"],
        "羊",
        [["Chinese", "羊"]],
    ),
    root(
        "yao",
        "want, need",
        ["transitive verb"],
        "要",
        [["Chinese", "要"]],
    ),
    root(
        "yas",
        "tooth",
        ["noun"],
        "牙",
        [["Chinese", "牙齿"]],
    ),
    root(
        "ye",
        "also, too",
        ["adverb"],
        "也",
        [["Chinese", "也"]],
    ),
    root(
        "yek",
        "eye, personality, character, soul",
        ["noun"],
        "眼",
        [["Chinese", "眼睛"]],
    ),
    root(
        "yen",
        "salt",
        ["noun"],
        "盐",
        [["Chinese", "盐"]],
    ),
    root(
        "yes",
        "yes, indeed",
        ["adverb"],
        "唉",
        [["English", "yes"]],
    ),
    root(
        "yo",
        "have, own, there is",
        ["existential"],
        "有",
        [["Chinese", "有"]],
        "y",
    ),
    root(
        "yoi",
        "(marginal interjection expressing surprise or dismay)",
        ["interjection"],
        "哎",
        [],
    ),
    root(
        "yok",
        "right (side)",
        ["positional"],
        "右",
        [["Chinese", "右边"]],
    ),
    root(
        "yon",
        "leap, jump, bounce",
        ["intransitive verb"],
        "踊",
        [["Chinese", "踊"]],
    ),
    root(
        "yos",
        "oil, fat, grease",
        ["noun"],
        "油",
        [["Chinese", "油脂"]],
    ),
    root(
        "yu",
        "fish",
        ["noun"],
        "鱼",
        [["Chinese", "鱼"]],
    ),
    root(
        "yuk",
        "help, assist",
        ["transitive verb"],
        "助",
        [["Spanish", "ayudar"]],
    ),
    root(
        "yun",
        "cloud, fog, mist, steam, vapor",
        ["noun"],
        "云",
        [["Chinese", "云"]],
    ),
    root(
        "yus",
        "use",
        ["transitive verb"],
        "用",
        [["English", "use"]],
    ),
]);

export function sourceCounts(): Map<SourceLanguage, number> {
    const out = new Map<SourceLanguage, number>([]);

    ROOTS.forEach((root, _) => {
        const sources = new Set<SourceLanguage>([]);
        root.etymologies.forEach(e => {
            sources.add(e.language);
        });
        sources.forEach(s => {
            out.set(s, (out.get(s) || 0) + 1)
        })
    })

    return out
}
